let source_root = if Sys.file_exists "db/migrations" then "." else "../.."
let thread_id = "T-00000000-0000-0000-0000-000000000008"
let counter = ref 0

let command program arguments =
  let argv = Array.of_list (program :: arguments) in
  let null = Unix.openfile "/dev/null" [ Unix.O_RDWR ] 0 in
  let pid = Unix.create_process program argv Unix.stdin null null in
  let _, status = Unix.waitpid [] pid in
  Unix.close null;
  match status with
  | Unix.WEXITED 0 -> ()
  | _ -> Alcotest.failf "%s failed" program

let git repo arguments = command "/usr/bin/git" ("-C" :: repo :: arguments)

let run_output program arguments =
  let output_path = Filename.temp_file "clamp-phase8-output" ".txt" in
  let output =
    Unix.openfile output_path [ Unix.O_WRONLY; Unix.O_TRUNC; Unix.O_CLOEXEC ]
      0o600
  in
  let argv = Array.of_list (program :: arguments) in
  let pid = Unix.create_process program argv Unix.stdin output Unix.stderr in
  Unix.close output;
  let _, status = Unix.waitpid [] pid in
  let channel = open_in_bin output_path in
  let text =
    Fun.protect ~finally:(fun () -> close_in channel) (fun () ->
        really_input_string channel (in_channel_length channel))
  in
  Sys.remove output_path;
  match status with
  | Unix.WEXITED 0 -> text
  | _ -> Alcotest.failf "%s output command failed" program

let git_output repo arguments =
  run_output "/usr/bin/git" ("-C" :: repo :: arguments) |> String.trim

let rec remove path =
  try
    match (Unix.lstat path).st_kind with
    | Unix.S_DIR ->
        Sys.readdir path
        |> Array.iter (fun name -> remove (Filename.concat path name));
        Unix.rmdir path
    | _ -> Unix.unlink path
  with Unix.Unix_error (Unix.ENOENT, _, _) -> ()

let mkdir_p path =
  let rec create current =
    if current <> Filename.dirname current && not (Sys.file_exists current)
    then begin
      create (Filename.dirname current);
      Unix.mkdir current 0o700
    end
  in
  create path

let write path contents =
  mkdir_p (Filename.dirname path);
  let channel = open_out_bin path in
  Fun.protect ~finally:(fun () -> close_out channel) (fun () ->
      output_string channel contents)

let read path =
  let channel = open_in_bin path in
  Fun.protect ~finally:(fun () -> close_in channel) (fun () ->
      really_input_string channel (in_channel_length channel))

let copy source destination = write destination (read source)

let contains text fragment =
  try
    ignore (Str.search_forward (Str.regexp_string fragment) text 0);
    true
  with Not_found -> false

let initial_fact body =
  Printf.sprintf
    "---\ntype: fact\ntitle: Initial durable fact\ngenerated: {by: amp/agent, at: 2026-08-27T08:00:00Z}\nclamp: {asserted_by: human:owner}\n---\n%s\n"
    body

let todo =
  "<!-- GENERATED by kb todo; DO NOT EDIT. -->\n# TODO\n\n## Doing\n\n_None._\n\n## Blocked\n\n_None._\n\n## Todo\n\n_None._\n"

type git_environment = {
  root : string;
  bare : string;
  writer : string;
  clone : string;
}

let commit_and_push env message =
  git env.writer [ "add"; "-A" ];
  git env.writer [ "commit"; "--quiet"; "-m"; message ];
  git env.writer [ "push"; "--quiet"; "origin"; "main" ];
  git_output env.writer [ "rev-parse"; "HEAD" ]

let with_git_environment label operation =
  incr counter;
  let root =
    Filename.concat (Filename.get_temp_dir_name ())
      (Printf.sprintf "clamp-phase8-%s-%d-%d" label (Unix.getpid ()) !counter)
  in
  remove root;
  Unix.mkdir root 0o700;
  let bare = Filename.concat root "remote.git"
  and writer = Filename.concat root "writer"
  and clone = Filename.concat root "clone" in
  command "/usr/bin/git"
    [ "init"; "--quiet"; "--bare"; "--initial-branch=main"; bare ];
  command "/usr/bin/git"
    [ "init"; "--quiet"; "--initial-branch=main"; writer ];
  git writer [ "config"; "user.name"; "Clamp Workflow Writer" ];
  git writer [ "config"; "user.email"; "writer@local.invalid" ];
  git writer [ "remote"; "add"; "origin"; bare ];
  let config =
    read (Filename.concat source_root "clamp.yaml")
    |> Str.global_replace
         (Str.regexp_string "github.com/gvrooyen/clamp")
         "local.test/clamp-fixture"
  in
  write (Filename.concat writer "clamp.yaml") config;
  write (Filename.concat writer ".gitignore") ".clamp/\n";
  write (Filename.concat writer "TODO.md") todo;
  write (Filename.concat writer "knowledge/facts/initial.md")
    (initial_fact "INITIAL_LOCAL_FALLBACK_SENTINEL.");
  let env = { root; bare; writer; clone } in
  ignore (commit_and_push env "initial Clamp workflow fixture");
  command "/usr/bin/git"
    [ "clone"; "--quiet"; "--depth"; "1"; "file://" ^ bare; clone ];
  git clone [ "config"; "user.name"; "Clamp Workflow Agent" ];
  git clone [ "config"; "user.email"; "agent@local.invalid" ];
  Fun.protect ~finally:(fun () -> remove root) (fun () -> operation env)

let quote_identifier value =
  "\"" ^ String.concat "\"\"" (String.split_on_char '"' value) ^ "\""

let target =
  lazy
    (match Clamp.Database.discover_local_target () with
    | Ok target -> target
    | Error failure -> Alcotest.failf "local target: %s" failure.message)

let user = (Unix.getpwuid (Unix.geteuid ())).pw_name

let connection database =
  let target = Lazy.force target in
  new Postgresql.connection ~host:target.socket_dir
    ~port:(string_of_int target.port) ~dbname:database ~user ()

let sql (connection : Postgresql.connection) statement =
  ignore (connection#exec ~expect:[ Postgresql.Command_ok ] statement)

let scalar (connection : Postgresql.connection) statement =
  let rows = connection#exec ~expect:[ Postgresql.Tuples_ok ] statement in
  rows#getvalue 0 0

let postgres database statement =
  let target = Lazy.force target in
  command "/usr/bin/sudo"
    [ "-u"; "postgres"; "/usr/bin/env"; "-i";
      "HOME=/var/lib/postgresql"; "USER=postgres"; "LOGNAME=postgres";
      "PATH=/usr/bin:/bin"; "PSQLRC=/dev/null"; "/usr/bin/psql";
      "--no-psqlrc"; "--quiet";
      "--set=ON_ERROR_STOP=1"; "--host"; target.socket_dir; "--port";
      string_of_int target.port; "--username"; "postgres"; "--dbname";
      database; "--command"; statement ]

let with_database env operation =
  let database =
    Printf.sprintf "clamp_p8_%d_%d" (Unix.getpid ()) !counter
  in
  let admin = connection "postgres" in
  sql admin ("CREATE DATABASE " ^ quote_identifier database);
  admin#finish;
  postgres database "CREATE EXTENSION vector WITH SCHEMA public";
  let migration_root = Filename.concat env.root "migration-root" in
  List.iter
    (fun name ->
      copy (Filename.concat source_root (Filename.concat "db/migrations" name))
        (Filename.concat migration_root (Filename.concat "db/migrations" name)))
    [ "0001_enable_vector.sql"; "0002_application_schema.sql" ];
  let active = ref None in
  Fun.protect
    ~finally:(fun () ->
      Option.iter
        (fun (connection : Postgresql.connection) ->
          try connection#finish with _ -> ())
        !active;
      postgres "postgres"
        ("DROP DATABASE IF EXISTS " ^ quote_identifier database ^ " WITH (FORCE)");
      remove migration_root)
    (fun () ->
      match Clamp.Database.migrate_local ~repo:migration_root ~database with
      | Error failure -> Alcotest.failf "migration: %s" failure.code
      | Ok _ ->
          let connection = connection database in
          active := Some connection;
          operation connection)

let vector () =
  let vector = Array.make Clamp.Openrouter.dimensions 0. in
  vector.(0) <- 1.;
  vector

let sync connection repo ?commit calls =
  Clamp.Sync.For_test.run_with_connection ~repo ~connection
    ~embed:(fun _ -> incr calls; Ok (vector ())) ~reembed:false
    ~allow_mass_deletion:false ~target_commit:commit

let check_sync label = function
  | Ok report -> report
  | Error (failure : Clamp.Sync.error) ->
      Alcotest.failf "%s: %s (%s)" label failure.message failure.code

let check_retrieval label = function
  | Ok value -> value
  | Error (failure : Clamp.Retrieval.error) ->
      Alcotest.failf "%s: %s (%s)" label failure.message failure.code

let kb_binary () =
  if Sys.file_exists "_build/default/bin/kb.exe" then
    "_build/default/bin/kb.exe"
  else "../../bin/kb.exe"

let capture_kb arguments =
  let output_path = Filename.temp_file "clamp-phase8-kb" ".out"
  and error_path = Filename.temp_file "clamp-phase8-kb" ".err" in
  let output =
    Unix.openfile output_path [ Unix.O_WRONLY; Unix.O_TRUNC; Unix.O_CLOEXEC ]
      0o600
  and errors =
    Unix.openfile error_path [ Unix.O_WRONLY; Unix.O_TRUNC; Unix.O_CLOEXEC ]
      0o600
  in
  let binary = kb_binary () in
  let environment =
    [| "PATH=/usr/bin:/bin"; "HOME=/nonexistent"; "LC_ALL=C"; "LANG=C" |]
  in
  let argv = Array.of_list (binary :: arguments) in
  let pid =
    Unix.create_process_env binary argv environment Unix.stdin output errors
  in
  Unix.close output;
  Unix.close errors;
  let _, status = Unix.waitpid [] pid in
  let stdout = read output_path and stderr = read error_path in
  Sys.remove output_path;
  Sys.remove error_path;
  status, stdout, stderr

let json_result expected_status expected_code arguments =
  let status, stdout, stderr = capture_kb arguments in
  Alcotest.(check bool) (expected_code ^ " status") true
    (status = Unix.WEXITED expected_status);
  Alcotest.(check string) (expected_code ^ " stderr") "" stderr;
  let json = Yojson.Safe.from_string stdout in
  Alcotest.(check string) (expected_code ^ " code") expected_code
    Yojson.Safe.Util.(json |> member "code" |> to_string);
  json

let disposable_end_to_end_workflow () =
  with_git_environment "end-to-end" (fun env ->
      with_database env (fun connection ->
          Alcotest.(check string) "fresh checkout is shallow" "true"
            (git_output env.clone [ "rev-parse"; "--is-shallow-repository" ]);
          let initial_calls = ref 0 in
          let initial =
            check_sync "fresh sync" (sync connection env.clone initial_calls)
          in
          Alcotest.(check int) "initial deterministic embedding" 1 !initial_calls;
          let search_calls = ref 0 in
          let search =
            check_retrieval "fresh search"
              (Clamp.Retrieval.For_test.search_with_connection ~connection
                 ~embed:(fun _ -> incr search_calls; Ok (vector ()))
                 ~source:"local.test/clamp-fixture"
                 ~local_commit:initial.commit ~query:"initial durable fact"
                 ~history:Clamp.Retrieval.normal_history)
          in
          Alcotest.(check int) "query embedded once" 1 !search_calls;
          Alcotest.(check (list string)) "fresh search finds durable fact"
            [ "facts/initial" ]
            (List.map (fun (result : Clamp.Retrieval.result) -> result.id) search);
          ignore
            (check_retrieval "fresh get"
               (Clamp.Retrieval.For_test.get_with_connection ~connection
                  ~source:"local.test/clamp-fixture"
                  ~local_commit:initial.commit ~id:"facts/initial"
                  ~history:Clamp.Retrieval.normal_history));
          Alcotest.(check string) "get records access" "1"
            (scalar connection
               "SELECT access_count::text FROM public.access_stats WHERE concept_path='facts/initial'");

          let explicit_input = Filename.concat env.root "explicit.md"
          and inferred_input = Filename.concat env.root "inferred.md"
          and auto_draft_input = Filename.concat env.root "auto-draft.md"
          and task_input = Filename.concat env.root "task.md" in
          write explicit_input
            "---\ntype: fact\ntitle: Explicit workflow fact\nclamp: {}\n---\nEXPLICIT_WORKFLOW_SENTINEL.\n";
          write inferred_input
            "---\ntype: fact\ntitle: Confirmed inferred workflow fact\nclamp: {}\n---\nCONFIRMED_INFERENCE_SENTINEL.\n";
          write auto_draft_input
            "---\ntype: fact\ntitle: Automatic draft workflow fact\nclamp: {}\n---\nAUTO_DRAFT_SENTINEL.\n";
          write task_input
            "---\ntype: task\ntitle: Verify the disposable Clamp workflow\nclamp:\n  task:\n    state: todo\n    priority: high\n---\nRun and verify the disposable workflow.\n";
          ignore
            (json_result 0 "concept_added"
               [ "add"; "facts/explicit-workflow"; "--repo"; env.clone;
                 "--input"; explicit_input; "--claim"; "explicit"; "--json" ]);
          let explicit_path =
            Filename.concat env.clone "knowledge/facts/explicit-workflow.md"
          in
          let explicit_before_verification = read explicit_path in
          ignore
            (json_result 2 "verification_authority_required"
               [ "verify"; "facts/explicit-workflow"; "--repo"; env.clone;
                 "--json" ]);
          ignore
            (json_result 2 "invalid_verification_authority"
               [ "verify"; "facts/explicit-workflow"; "--repo"; env.clone;
                 "--verification-authority"; "agent-reviewed"; "--json" ]);
          Alcotest.(check string) "agent review cannot mutate human verification"
            explicit_before_verification (read explicit_path);
          ignore
            (json_result 0 "concept_verified"
               [ "verify"; "facts/explicit-workflow"; "--repo"; env.clone;
                 "--verification-authority"; "user-explicit"; "--json" ]);
          let verified_document =
            Clamp.Frontmatter.parse (read explicit_path) |> Result.get_ok
          in
          let verified_by =
            match Clamp.Local.verification_events verified_document.metadata with
            | [ event ] ->
                Option.bind (Clamp.Exact_yaml.find "by" event)
                  Clamp.Exact_yaml.string
            | _ -> None
          in
          Alcotest.(check (option string))
            "only explicit user authority records human verification"
            (Some "human:owner") verified_by;
          ignore
            (json_result 2 "confirmation_required"
               [ "add"; "facts/confirmed-inference"; "--repo"; env.clone;
                 "--input"; inferred_input; "--claim"; "inferred"; "--json" ]);
          Alcotest.(check bool) "unconfirmed inference made no write" false
            (Sys.file_exists
               (Filename.concat env.clone
                  "knowledge/facts/confirmed-inference.md"));
          ignore
            (json_result 0 "concept_added"
               [ "add"; "facts/confirmed-inference"; "--repo"; env.clone;
                 "--input"; inferred_input; "--claim"; "inferred";
                 "--confirmed"; "--json" ]);
          ignore
            (json_result 0 "config_updated"
               [ "config"; "set"; "inferred-writes"; "auto_draft";
                 "--direct-user-intent"; "--repo"; env.clone; "--json" ]);
          ignore
            (json_result 0 "concept_added"
               [ "add"; "facts/automatic-draft"; "--repo"; env.clone;
                 "--input"; auto_draft_input; "--claim"; "inferred";
                 "--json" ]);
          let automatic_draft =
            Filename.concat env.clone "knowledge/facts/automatic-draft.md"
            |> read |> Clamp.Frontmatter.parse |> Result.get_ok
          in
          Alcotest.(check (option string)) "auto_draft creates a draft"
            (Some "draft")
            (Option.bind
               (Clamp.Exact_yaml.find "status" automatic_draft.metadata)
               Clamp.Exact_yaml.string);
          Alcotest.(check int) "auto_draft creates no human verification" 0
            (Clamp.Local.verification_events automatic_draft.metadata
            |> List.length);
          ignore
            (json_result 0 "config_updated"
               [ "config"; "set"; "inferred-writes"; "confirm";
                 "--direct-user-intent"; "--repo"; env.clone; "--json" ]);
          let task_json =
            json_result 0 "task_added"
              [ "task"; "add"; "--repo"; env.clone; "--input"; task_input;
                "--claim"; "explicit"; "--json" ]
          in
          let task_id =
            Yojson.Safe.Util.(task_json |> member "data" |> member "id" |> to_string)
          in
          Alcotest.(check bool) "returned task ID already includes namespace" true
            (String.starts_with ~prefix:"tasks/" task_id);
          ignore
            (json_result 0 "task_started"
               [ "task"; "start"; task_id; "--repo"; env.clone; "--json" ]);
          Alcotest.(check bool) "TODO updated through task command" true
            (contains (read (Filename.concat env.clone "TODO.md"))
               "Verify the disposable Clamp workflow");
          ignore
            (json_result 0 "task_done"
               [ "task"; "done"; task_id; "--repo"; env.clone;
                 "--closure-authority"; "performed-and-verified"; "--json" ]);
          Alcotest.(check bool) "closed task omitted from generated TODO" false
            (contains (read (Filename.concat env.clone "TODO.md"))
               "Verify the disposable Clamp workflow");
          ignore
            (json_result 0 "bundle_valid"
               [ "validate"; "--repo"; env.clone; "--json" ]);

          let publication_calls = ref 0 in
          let publication =
            Clamp.Publication.For_test.run ~repo:env.clone ~thread_id
              ~preserve_conflict:false
              ~sync:(fun commit ->
                sync connection env.clone ~commit publication_calls)
              ~hooks:Clamp.Publication.For_test.default_hooks
          in
          let published =
            match publication with
            | Ok report -> report
            | Error (failure : Clamp.Publication.error) ->
                Alcotest.failf "publication: %s (%s)" failure.message
                  failure.code
          in
          Alcotest.(check string) "publication durable on bare main"
            published.commit
            (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
          Alcotest.(check string) "publication exact-SHA sync" published.commit
            published.sync.commit;
          Alcotest.(check int) "new concepts embedded on publication" 4
            !publication_calls;
          let rerun_calls = ref 0 in
          let rerun =
            check_sync "post-publication resync"
              (sync connection env.clone rerun_calls)
          in
          Alcotest.(check string) "resync exact commit" published.commit
            rerun.commit;
          Alcotest.(check int) "resync embeds nothing" 0 !rerun_calls;
          Alcotest.(check int) "all five concepts unchanged" 5
            rerun.counts.unchanged;
          let indexed =
            check_retrieval "published fact search"
              (Clamp.Retrieval.For_test.search_with_connection ~connection
                 ~embed:(fun _ -> Ok (vector ()))
                 ~source:"local.test/clamp-fixture"
                 ~local_commit:published.commit ~query:"explicit workflow"
                 ~history:Clamp.Retrieval.normal_history)
          in
          Alcotest.(check bool) "published explicit fact is searchable" true
            (List.exists
               (fun (result : Clamp.Retrieval.result) ->
                 result.id = "facts/explicit-workflow")
               indexed);
          let retrieved =
            check_retrieval "published fact get"
              (Clamp.Retrieval.For_test.get_with_connection ~connection
                 ~source:"local.test/clamp-fixture"
                 ~local_commit:published.commit ~id:"facts/explicit-workflow"
                 ~history:Clamp.Retrieval.normal_history)
          in
          Alcotest.(check bool) "published full content returned" true
            (contains retrieved.body "EXPLICIT_WORKFLOW_SENTINEL")))

let degraded_local_fallback () =
  with_git_environment "fallback" (fun env ->
      let sync_json =
        json_result 2 "database_direct_url_missing"
          [ "sync"; "--repo"; env.clone; "--json" ]
      in
      let open Yojson.Safe.Util in
      let sync_details = sync_json |> member "details" in
      Alcotest.(check string) "first sync has structured fallback"
        "local_markdown_or_rg"
        (sync_details |> member "fallback" |> to_string);
      Alcotest.(check bool) "first sync fallback is non-semantic" false
        (sync_details |> member "semantic_equivalent" |> to_bool);
      let json =
        json_result 2 "database_url_missing"
          [ "search"; "initial fallback sentinel"; "--repo"; env.clone;
            "--json" ]
      in
      let details = json |> member "details" in
      Alcotest.(check string) "classified fallback"
        "local_markdown_or_rg" (details |> member "fallback" |> to_string);
      Alcotest.(check bool) "fallback is explicitly non-semantic" false
        (details |> member "semantic_equivalent" |> to_bool);
      let rg =
        if Sys.file_exists "/usr/local/bin/rg" then "/usr/local/bin/rg"
        else "/usr/bin/rg"
      in
      let matches =
        run_output rg
          [ "-n"; "-i"; "--glob"; "*.md"; "--";
            "initial_local_fallback_sentinel";
            Filename.concat env.clone "knowledge" ]
      in
      Alcotest.(check bool) "local rg finds durable Markdown" true
        (contains matches "knowledge/facts/initial.md");
      let simulated =
        Clamp.Retrieval.cli_result
          { Clamp.Retrieval.kind = Transient; code = "database_unavailable";
            message = "fixture outage" }
        |> Clamp.Cli_result.to_yojson
      in
      let simulated_details = simulated |> member "details" in
      Alcotest.(check string) "transient outage uses same fallback"
        "local_markdown_or_rg"
        (simulated_details |> member "fallback" |> to_string);
      Alcotest.(check bool) "transient fallback remains non-semantic" false
        (simulated_details |> member "semantic_equivalent" |> to_bool))

let conflict_preservation_before_email_request () =
  with_git_environment "conflict-email" (fun env ->
      let local_body = "LOCAL_CONFLICT_BODY_MUST_NOT_BE_EMAILED" in
      write (Filename.concat env.clone "knowledge/facts/initial.md")
        (initial_fact local_body);
      write (Filename.concat env.writer "knowledge/facts/initial.md")
        (initial_fact "Remote conflicting body.");
      ignore (commit_and_push env "remote conflicting update");
      let sync commit =
        Ok
          { Clamp.Sync.commit;
            counts =
              { added = 0; metadata_updated = 0; reembedded = 0;
                unchanged = 0; deleted = 0 };
            rebuilt = false; diagnostics = [] }
      in
      let pending =
        Clamp.Publication.For_test.run ~repo:env.clone ~thread_id
          ~preserve_conflict:false ~sync
          ~hooks:Clamp.Publication.For_test.default_hooks
      in
      let pending =
        match pending with
        | Ok _ -> Alcotest.fail "expected semantic publication conflict"
        | Error failure ->
            Alcotest.(check string) "unpreserved conflict code"
              "publish_conflict" failure.code;
            failure
      in
      let hooks =
        { Clamp.Publication.For_test.default_hooks with
          now = (fun () -> 1_787_832_000.) }
      in
      let preserved =
        Clamp.Publication.For_test.run ~repo:env.clone ~thread_id
          ~preserve_conflict:true ~sync ~hooks
      in
      let preserved =
        match preserved with
        | Ok _ -> Alcotest.fail "preservation returns the conflict exit class"
        | Error failure ->
            Alcotest.(check string) "preserved conflict code"
              "publish_conflict_preserved" failure.code;
            failure
      in
      let branch = Option.get preserved.branch
      and commit = Option.get preserved.commit in
      Alcotest.(check string) "preserved remote ref contains original commit"
        commit (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check (list string)) "preserved body-free paths"
        [ "knowledge/facts/initial.md" ] preserved.paths;
      let sent = Hashtbl.create 1 and requests = ref [] in
      let request_email (failure : Clamp.Publication.error) =
        match failure.code, failure.branch, failure.commit with
        | ( ( "publish_conflict_preserved"
            | "publish_conflict_preserved_cleanup_pending" ),
            Some branch, Some commit )
          when failure.preserved ->
            let key = branch ^ "\000" ^ commit in
            if not (Hashtbl.mem sent key) then begin
              Hashtbl.add sent key ();
              let thread_url =
                "https://ampcode.com/threads/" ^ thread_id
              in
              let text =
                String.concat "\n"
                  ([ "Thread: " ^ thread_url; "Conflict ref: " ^ branch;
                     "Preserved commit: " ^ commit; "Paths:" ]
                   @ List.map (fun path -> "- " ^ path) failure.paths)
              in
              requests :=
                `Assoc
                  [ ("operation", `String "new");
                    ( "subject",
                      `String
                        "[Clamp] Knowledge update needs conflict resolution" );
                    ("text", `String text) ]
                :: !requests
            end
        | _ -> ()
      in
      request_email pending;
      Alcotest.(check int) "no request before preservation" 0
        (List.length !requests);
      request_email preserved;
      request_email preserved;
      Alcotest.(check int) "exactly one request after preservation" 1
        (List.length !requests);
      let request = List.hd !requests in
      let open Yojson.Safe.Util in
      Alcotest.(check string) "new owner-email operation" "new"
        (request |> member "operation" |> to_string);
      Alcotest.(check string) "exact owner-email subject"
        "[Clamp] Knowledge update needs conflict resolution"
        (request |> member "subject" |> to_string);
      Alcotest.(check bool) "no recipient field" true
        (request |> member "recipient" = `Null);
      let text = request |> member "text" |> to_string in
      List.iter
        (fun value ->
          Alcotest.(check bool) ("email includes " ^ value) true
            (contains text value))
        [ "https://ampcode.com/threads/" ^ thread_id; branch; commit;
          "knowledge/facts/initial.md" ];
      List.iter
        (fun value ->
          Alcotest.(check bool) ("email excludes " ^ value) false
            (contains text value))
        [ local_body; "Remote conflicting body"; "OPENROUTER_API_KEY";
          "KB_DATABASE_URL"; "postgresql://" ])

let () =
  Alcotest.run "Phase 8 end-to-end agent workflow"
    [ ( "workflow",
        [ Alcotest.test_case "fresh sync through publish and resync" `Quick
            disposable_end_to_end_workflow;
          Alcotest.test_case "classified outage uses local fallback" `Quick
            degraded_local_fallback;
          Alcotest.test_case "conflict preservation gates one email request"
            `Quick conflict_preservation_before_email_request ] ) ]
