let source_root = if Sys.file_exists "clamp.yaml" then "." else "../.."
let thread_id = "T-00000000-0000-0000-0000-000000000007"
let counter = ref 0

let command program arguments =
  let argv = Array.of_list (program :: arguments) in
  let null = Unix.openfile "/dev/null" [ Unix.O_RDWR ] 0 in
  let pid = Unix.create_process program argv Unix.stdin null null in
  let _, status = Unix.waitpid [] pid in
  Unix.close null;
  match status with
  | Unix.WEXITED 0 -> ()
  | _ -> Alcotest.failf "%s failed" program

let git repo arguments = command "/usr/bin/git" ("-C" :: repo :: arguments)

let git_succeeds repo arguments =
  let argv = Array.of_list ("git" :: "-C" :: repo :: arguments) in
  let null = Unix.openfile "/dev/null" [ Unix.O_RDWR ] 0 in
  let pid = Unix.create_process "/usr/bin/git" argv Unix.stdin null null in
  let _, status = Unix.waitpid [] pid in
  Unix.close null;
  status = Unix.WEXITED 0

let contains text fragment =
  try ignore (Str.search_forward (Str.regexp_string fragment) text 0); true
  with Not_found -> false

let git_output_raw repo arguments =
  let input, output = Unix.pipe ~cloexec:true () in
  let argv = Array.of_list ("git" :: "-C" :: repo :: arguments) in
  let pid = Unix.create_process "/usr/bin/git" argv Unix.stdin output Unix.stderr in
  Unix.close output;
  let channel = Unix.in_channel_of_descr input in
  let text =
    Fun.protect ~finally:(fun () -> close_in_noerr channel) (fun () ->
        let buffer = Buffer.create 128 in
        (try while true do Buffer.add_channel buffer channel 4096 done
         with End_of_file -> ());
        Buffer.contents buffer)
  in
  match snd (Unix.waitpid [] pid) with
  | Unix.WEXITED 0 -> text
  | _ -> Alcotest.fail "git output command failed"

let git_output repo arguments = String.trim (git_output_raw repo arguments)

let rec remove path =
  try
    match (Unix.lstat path).st_kind with
    | Unix.S_DIR ->
        Sys.readdir path
        |> Array.iter (fun name -> remove (Filename.concat path name));
        Unix.rmdir path
    | _ -> Unix.unlink path
  with Unix.Unix_error (Unix.ENOENT, _, _) -> ()

let mkdir_p path =
  let rec create current =
    if current <> Filename.dirname current && not (Sys.file_exists current)
    then begin create (Filename.dirname current); Unix.mkdir current 0o700 end
  in
  create path

let write path contents =
  mkdir_p (Filename.dirname path);
  let channel = open_out_bin path in
  Fun.protect ~finally:(fun () -> close_out channel) (fun () ->
      output_string channel contents)

let read path =
  let channel = open_in_bin path in
  Fun.protect ~finally:(fun () -> close_in channel) (fun () ->
      really_input_string channel (in_channel_length channel))

let fact title body =
  Printf.sprintf
    "---\ntype: fact\ntitle: %s\ngenerated: {by: amp/agent, at: 2026-08-26T08:00:00Z}\nclamp: {asserted_by: human:test}\n---\n%s\n"
    title body

let task title =
  Printf.sprintf
    "---\ntype: task\ntitle: %s\ngenerated: {by: amp/agent, at: 2026-08-26T08:00:00Z}\nclamp: {asserted_by: human:test, task: {state: todo, priority: normal}}\n---\nTask body.\n"
    title

let todo =
  "<!-- GENERATED by kb todo; DO NOT EDIT. -->\n# TODO\n\n## Doing\n\n_None._\n\n## Blocked\n\n_None._\n\n## Todo\n\n_None._\n"

type environment = {
  root : string;
  bare : string;
  writer : string;
  clone : string;
}

let commit_writer env message =
  git env.writer [ "add"; "-A" ];
  git env.writer [ "commit"; "--quiet"; "-m"; message ];
  git env.writer [ "push"; "--quiet"; "origin"; "main" ];
  git_output env.writer [ "rev-parse"; "HEAD" ]

let advance_writer env index ?(same = false) () =
  git env.writer [ "fetch"; "--quiet"; "origin"; "main" ];
  git env.writer [ "reset"; "--quiet"; "--hard"; "origin/main" ];
  let path =
    if same then "knowledge/facts/same.md"
    else Printf.sprintf "knowledge/facts/winner-%d.md" index
  in
  write (Filename.concat env.writer path)
    (fact (Printf.sprintf "Winner %d" index)
       (Printf.sprintf "Remote winner %d." index));
  commit_writer env (Printf.sprintf "writer %d" index)

let with_environment ?attributes label operation =
  incr counter;
  let root =
    Filename.concat (Filename.get_temp_dir_name ())
      (Printf.sprintf "clamp-phase7-%s-%d-%d" label (Unix.getpid ()) !counter)
  in
  remove root; Unix.mkdir root 0o700;
  let bare = Filename.concat root "remote.git"
  and writer = Filename.concat root "writer"
  and clone = Filename.concat root "clone" in
  command "/usr/bin/git"
    [ "init"; "--quiet"; "--bare"; "--initial-branch=main"; bare ];
  command "/usr/bin/git"
    [ "init"; "--quiet"; "--initial-branch=main"; writer ];
  git writer [ "config"; "user.name"; "Clamp Writer" ];
  git writer [ "config"; "user.email"; "writer@local.invalid" ];
  git writer [ "remote"; "add"; "origin"; bare ];
  let config =
    read (Filename.concat source_root "clamp.yaml")
    |> Str.global_replace
         (Str.regexp_string "github.com/gvrooyen/clamp")
         "local.test/clamp-fixture"
  in
  write (Filename.concat writer "clamp.yaml") config;
  Option.iter
    (fun contents -> write (Filename.concat writer ".gitattributes") contents)
    attributes;
  write (Filename.concat writer "TODO.md") todo;
  write (Filename.concat writer "README.fixture") "fixture\n";
  write (Filename.concat writer "knowledge/facts/same.md") (fact "Same" "Base.");
  let env = { root; bare; writer; clone } in
  ignore (commit_writer env "initial");
  command "/usr/bin/git"
    [ "clone"; "--quiet"; "--depth"; "1"; "file://" ^ bare; clone ];
  git clone [ "config"; "user.name"; "Clamp Publisher" ];
  git clone [ "config"; "user.email"; "publisher@local.invalid" ];
  Fun.protect ~finally:(fun () -> remove root) (fun () -> operation env)

let empty_counts =
  { Clamp.Sync.added = 0; metadata_updated = 0; reembedded = 0;
    unchanged = 0; deleted = 0 }

let successful_sync commit =
  Ok
    { Clamp.Sync.commit; counts = empty_counts; rebuilt = false;
      diagnostics = [] }

let run ?(preserve = false) ?(hooks = Clamp.Publication.For_test.default_hooks)
    ?(sync = successful_sync) env =
  Clamp.Publication.For_test.run ~repo:env.clone ~thread_id
    ~preserve_conflict:preserve ~sync ~hooks

let capture_binary binary arguments =
  let output_path = Filename.temp_file "clamp-p7-cli" ".out"
  and error_path = Filename.temp_file "clamp-p7-cli" ".err" in
  let output = Unix.openfile output_path [ Unix.O_WRONLY; Unix.O_TRUNC ] 0o600
  and errors = Unix.openfile error_path [ Unix.O_WRONLY; Unix.O_TRUNC ] 0o600 in
  let environment =
    [| "PATH=/usr/bin:/bin"; "HOME=/nonexistent"; "LC_ALL=C"; "LANG=C" |]
  in
  let argv = Array.of_list (binary :: arguments) in
  let pid =
    Unix.create_process_env binary argv environment Unix.stdin output errors
  in
  Unix.close output; Unix.close errors;
  let _, status = Unix.waitpid [] pid in
  let stdout = read output_path and stderr = read error_path in
  Sys.remove output_path; Sys.remove error_path;
  (status, stdout, stderr)

let capture_cli arguments =
  let binary =
    if Sys.file_exists "_build/default/bin/kb.exe" then
      "_build/default/bin/kb.exe"
    else "../../bin/kb.exe"
  in
  capture_binary binary arguments

let check_ok label = function
  | Ok (report : Clamp.Publication.report) -> report
  | Error (error : Clamp.Publication.error) ->
      Alcotest.failf "%s: %s (%s)" label error.message error.code

let check_error label code = function
  | Ok _ -> Alcotest.failf "%s: expected %s" label code
  | Error (error : Clamp.Publication.error) ->
      Alcotest.(check string) label code error.code;
      error

let local_change env name =
  write (Filename.concat env.clone ("knowledge/facts/" ^ name ^ ".md"))
    (fact name ("Local " ^ name ^ "."))

let publication_refs env =
  git_output env.clone
    [ "for-each-ref"; "--format=%(refname)"; "refs/clamp/publish/" ]

let publication_state_ref =
  "refs/clamp/publish/" ^ thread_id ^ "/state"

let publication_original_ref =
  "refs/clamp/publish/" ^ thread_id ^ "/original"

let publication_state_body env =
  git_output_raw env.clone
    [ "cat-file"; "blob";
      git_output env.clone [ "rev-parse"; publication_state_ref ] ]

let v3_body_to_v1 body =
  match String.split_on_char '\000' body with
  | "clamp-publish-state-v3" :: races
    :: ("none" | "legacy_unresolved") :: "" :: rest ->
      Some (String.concat "\000" ("clamp-publish-state-v1" :: races :: rest))
  | _ -> None

let downgrade_publication_state_to_v1 env =
  let old_object = git_output env.clone [ "rev-parse"; publication_state_ref ] in
  let v3_body = publication_state_body env in
  let v1_body =
    match v3_body_to_v1 v3_body with
    | Some body -> body
    | None ->
        Alcotest.fail
          "only unallocated not-started or legacy v3 state can be downgraded to v1"
  in
  let body_path = Filename.concat env.root "publication-state-v1.bin" in
  write body_path v1_body;
  let v1_object =
    git_output env.clone [ "hash-object"; "-w"; "--"; body_path ]
  in
  git env.clone
    [ "update-ref"; publication_state_ref; v1_object; old_object ];
  Alcotest.(check string) "installed exact v1 state body" v1_body
    (publication_state_body env);
  v1_body, v1_object

let check_v1_migrated_exactly label env v1_body =
  let v3_body = publication_state_body env in
  Alcotest.(check bool) (label ^ " has v3 magic") true
    (String.starts_with ~prefix:"clamp-publish-state-v3\000" v3_body);
  let reconstructed = v3_body_to_v1 v3_body in
  Alcotest.(check (option string)) (label ^ " preserves every v1 field")
    (Some v1_body) reconstructed

let v3_body_to_v2 body =
  match String.split_on_char '\000' body with
  | "clamp-publish-state-v3" :: races :: status :: branch :: rest
    when List.mem status
           [ "none"; "legacy_unresolved"; "push_pending"; "proven" ] ->
      Some
        (String.concat "\000"
           ("clamp-publish-state-v2" :: races :: branch :: rest))
  | _ -> None

let downgrade_publication_state_to_v2 env =
  let old_object = git_output env.clone [ "rev-parse"; publication_state_ref ] in
  let v2_body =
    match v3_body_to_v2 (publication_state_body env) with
    | Some body -> body
    | None -> Alcotest.fail "current publication state cannot be encoded as v2"
  in
  let body_path = Filename.concat env.root "publication-state-v2.bin" in
  write body_path v2_body;
  let v2_object =
    git_output env.clone [ "hash-object"; "-w"; "--"; body_path ]
  in
  git env.clone
    [ "update-ref"; publication_state_ref; v2_object; old_object ];
  v2_body, v2_object

let clean_and_outdated () =
  with_environment "clean" (fun env ->
      Alcotest.(check string) "shallow clone" "true"
        (git_output env.clone [ "rev-parse"; "--is-shallow-repository" ]);
      local_change env "clean";
      let synced = ref None in
      let report =
        check_ok "clean publish"
          (run ~sync:(fun commit -> synced := Some commit; successful_sync commit) env)
      in
      Alcotest.(check string) "remote exact commit" report.commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check (option string)) "exact SHA passed to sync"
        (Some report.commit) !synced);
  with_environment "outdated" (fun env ->
      local_change env "local";
      ignore (advance_writer env 1 ());
      let report = check_ok "outdated publish" (run env) in
      ignore (git_output env.bare
                [ "show"; report.commit ^ ":knowledge/facts/local.md" ]);
      ignore (git_output env.bare
                [ "show"; report.commit ^ ":knowledge/facts/winner-1.md" ]));
  with_environment "known-outdated" (fun env ->
      ignore (advance_writer env 2 ());
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      let head = git_output env.clone [ "rev-parse"; "HEAD" ]
      and tracked =
        git_output env.clone [ "rev-parse"; "refs/remotes/origin/main" ]
      in
      Alcotest.(check bool) "local main is strictly behind tracking" true
        (head <> tracked
         && git_succeeds env.clone
              [ "merge-base"; "--is-ancestor"; head; tracked ]);
      local_change env "known-behind-local";
      let synced = ref None in
      let report =
        check_ok "known-behind publish"
          (run ~sync:(fun commit -> synced := Some commit; successful_sync commit)
             env)
      in
      Alcotest.(check string) "known-behind exact remote result" report.commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check string) "known-behind exact sync result" "sync_complete"
        (Clamp.Sync.completion_code report.sync);
      Alcotest.(check (option string)) "known-behind exact sync SHA"
        (Some report.commit) !synced;
      ignore
        (git_output env.bare
           [ "show"; report.commit ^ ":knowledge/facts/winner-2.md" ]);
      ignore
        (git_output env.bare
           [ "show";
             report.commit ^ ":knowledge/facts/known-behind-local.md" ]);
      Alcotest.(check string) "known-behind terminal state cleaned" ""
        (publication_refs env))

let managed_deletion () =
  with_environment "managed-deletion" (fun env ->
      write (Filename.concat env.writer "knowledge/facts/retained.md")
        (fact "Retained" "Retained baseline concept.");
      ignore (commit_writer env "add retained baseline concept");
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
      Sys.remove (Filename.concat env.clone "knowledge/facts/same.md");
      let synced = ref None in
      let report =
        check_ok "managed deletion publish"
          (run ~sync:(fun commit -> synced := Some commit; successful_sync commit)
             env)
      in
      Alcotest.(check string) "deletion exact remote result" report.commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check (option string)) "deletion exact sync SHA"
        (Some report.commit) !synced;
      Alcotest.(check bool) "managed deletion committed" false
        (git_succeeds env.bare
           [ "cat-file"; "-e";
             report.commit ^ ":knowledge/facts/same.md" ]);
      Alcotest.(check string) "deletion terminal state cleaned" ""
        (publication_refs env))

let exact_bytes_and_transform_guard () =
  with_environment
    ~attributes:"knowledge/** filter=marker\n"
    "exact-bytes" (fun env ->
      let marker = Filename.concat env.root "filter-ran"
      and helper = Filename.concat env.root "filter-marker" in
      write helper
        (Printf.sprintf "#!/bin/sh\nprintf ran > %s\ncat\n" marker);
      Unix.chmod helper 0o700;
      git env.clone [ "config"; "filter.marker.clean"; helper ];
      git env.clone [ "config"; "filter.marker.smudge"; helper ];
      let expected =
        fact "Exact bytes" "CRLF bytes remain exact."
        |> Str.global_replace (Str.regexp_string "\n") "\r\n"
      in
      write (Filename.concat env.clone "knowledge/facts/exact-bytes.md") expected;
      ignore
        (check_error "transform configuration"
           "publish_transform_config_unsafe" (run env));
      Alcotest.(check bool) "configured helper never ran" false
        (Sys.file_exists marker);
      Alcotest.(check string) "preflight did not commit"
        (git_output env.clone [ "rev-parse"; "refs/remotes/origin/main" ])
        (git_output env.clone [ "rev-parse"; "HEAD" ]);
      git env.clone [ "config"; "--unset-all"; "filter.marker.clean" ];
      git env.clone [ "config"; "--unset-all"; "filter.marker.smudge" ];
      let report = check_ok "exact-byte publish" (run env) in
      Alcotest.(check string) "committed blob is exact validated snapshot"
        expected
        (git_output_raw env.bare
           [ "show"; report.commit ^ ":knowledge/facts/exact-bytes.md" ]);
      Alcotest.(check bool) "helper stayed inert" false (Sys.file_exists marker);
      Alcotest.(check string) "successful terminal state cleaned" ""
        (publication_refs env))

let post_rebase_validation () =
  with_environment "post-rebase-todo" (fun env ->
      local_change env "pending";
      let remote_task =
        "knowledge/tasks/01ARZ3NDEKTSV4RRFFQ69G5FAX-remote-drift.md"
      in
      write (Filename.concat env.writer remote_task) (task "Remote drift task");
      ignore (commit_writer env "remote task without generated TODO");
      let report = check_ok "clean rebase TODO repair" (run env) in
      let rendered =
        git_output_raw env.bare [ "show"; report.commit ^ ":TODO.md" ]
      in
      Alcotest.(check bool) "rebased task rendered" true
        (contains rendered "Remote drift task"));
  with_environment "post-rebase-collision" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/case.md")
        (fact "Lower case" "Local case path.");
      write (Filename.concat env.writer "knowledge/facts/Case.md")
        (fact "Upper case" "Remote case path.");
      let remote = commit_writer env "remote case path" in
      ignore
        (check_error "post-rebase case collision" "publish_validation_failed"
           (run env));
      Alcotest.(check string) "invalid candidate not pushed" remote
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]))

let clean_races_and_recovery () =
  with_environment "one-race" (fun env ->
      local_change env "race-local";
      let refs = ref [] in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec ->
              refs := refspec :: !refs;
              if attempt = 1 then ignore (advance_writer env 1 ()));
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> ()); now = (fun () -> 1_787_733_723.) }
      in
      ignore (check_ok "one race" (run ~hooks env));
      Alcotest.(check int) "two main pushes" 2 (List.length !refs);
      List.iter
        (fun refspec ->
          Alcotest.(check bool) "no force refspec" false
            (String.starts_with ~prefix:"+" refspec
             || String.contains refspec ' '))
        !refs);
  with_environment "three-races" (fun env ->
      local_change env "pending";
      let main_attempts = ref 0 and observed = ref [] in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec ->
              observed := (attempt, refspec) :: !observed;
              if attempt <= 3 then begin
                incr main_attempts;
                ignore (advance_writer env attempt ())
              end);
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> Alcotest.fail "race exhaustion synced");
          now = (fun () -> 1_787_733_723.) }
      in
      let error = check_error "race exhaustion" "publish_race_exhausted"
          (run ~hooks env) in
      Alcotest.(check int) "exactly three races" 3 !main_attempts;
      let branch = Option.get error.branch and commit = Option.get error.commit in
      Alcotest.(check string) "recovery ref commit" commit
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      ignore (git_output env.bare
                [ "show"; commit ^ ":knowledge/facts/pending.md" ]);
      for index = 1 to 3 do
        ignore (git_output env.bare
                  [ "show";
                    Printf.sprintf "%s:knowledge/facts/winner-%d.md" commit index ])
      done;
      let main = git_output env.bare [ "rev-parse"; "refs/heads/main" ] in
      let missing =
        not (git_succeeds env.bare
               [ "cat-file"; "-e"; main ^ ":knowledge/facts/pending.md" ])
      in
      Alcotest.(check bool) "pending absent from main" true missing;
      List.iter
        (fun (_, refspec) ->
          Alcotest.(check bool) "no force path" false
            (String.starts_with ~prefix:"+" refspec
             || String.contains refspec ' '))
        !observed;
      Alcotest.(check string) "recovery terminal state cleaned" ""
        (publication_refs env))

let todo_conflict () =
  with_environment "todo" (fun env ->
      let first =
        "knowledge/tasks/01ARZ3NDEKTSV4RRFFQ69G5FAV-local-task.md"
      and second =
        "knowledge/tasks/01ARZ3NDEKTSV4RRFFQ69G5FAW-remote-task.md"
      in
      write (Filename.concat env.clone first) (task "Local task");
      ignore (Clamp.Local.todo env.clone);
      write (Filename.concat env.writer second) (task "Remote task");
      ignore (Clamp.Local.todo env.writer);
      ignore (commit_writer env "remote task");
      let report = check_ok "generated TODO conflict" (run env) in
      let rendered =
        git_output env.bare [ "show"; report.commit ^ ":TODO.md" ]
      in
      Alcotest.(check bool) "local task rendered" true
        (contains rendered "Local task");
      Alcotest.(check bool) "remote task rendered" true
        (contains rendered "Remote task");
      Alcotest.(check bool) "no conflict marker" false
        (contains rendered "<<<<<<<"))

let conflict_resolution_and_preservation () =
  with_environment "resolve" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Local version.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote version.");
      ignore (commit_writer env "remote conflict");
      let pending = check_error "pending conflict" "publish_conflict" (run env) in
      Alcotest.(check (list string)) "safe paths"
        [ "knowledge/facts/same.md" ] pending.paths;
      let expected =
        fact "Same" "Semantically resolved local and remote versions."
      in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        expected;
      git env.clone [ "add"; "--"; "knowledge/facts/same.md" ];
      let report = check_ok "resolved retry" (run env) in
      let body =
        git_output_raw env.bare
          [ "show"; report.commit ^ ":knowledge/facts/same.md" ]
      in
      Alcotest.(check string) "exact semantic resolution" expected body);
  with_environment "preserve" (fun env ->
      let local_body = "LOCAL_BODY_SENTINEL_NEVER_IN_ERROR" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" local_body);
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote version.");
      ignore (commit_writer env "remote conflict");
      let pending = check_error "unresolved" "publish_conflict" (run env) in
      let original = Option.get pending.commit in
      Alcotest.(check bool) "body absent from error" false
        (String.contains pending.message 'L');
      let preserved =
        check_error "preserved" "publish_conflict_preserved"
          (run ~preserve:true env)
      in
      let branch = Option.get preserved.branch in
      Alcotest.(check string) "original commit preserved" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check string) "original content preserved" local_body
        (git_output env.bare
           [ "show"; "refs/heads/" ^ branch ^ ":knowledge/facts/same.md" ]
         |> fun document ->
         document |> String.split_on_char '\n' |> List.rev |> List.hd);
      Alcotest.(check string) "conflict terminal state cleaned" ""
        (publication_refs env));
  with_environment "race-conflict" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Original local version.");
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec:_ ->
              if attempt = 1 then ignore (advance_writer env 1 ())
              else if attempt = 2 then
                ignore (advance_writer env 2 ~same:true ()));
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> ()); now = Unix.gettimeofday }
      in
      let pending =
        check_error "post-race conflict" "publish_conflict" (run ~hooks env)
      in
      let original = Option.get pending.commit in
      let preserved =
        check_error "post-race original preserved" "publish_conflict_preserved"
          (run ~preserve:true env)
      in
      Alcotest.(check string) "pre-first-rebase commit preserved" original
        (git_output env.bare
           [ "rev-parse"; "refs/heads/" ^ Option.get preserved.branch ]))

let conflict_preservation_cleanup_recovery () =
  with_environment "preserved-cleanup-recovery" (fun env ->
      let local_body = "PRESERVED_CLEANUP_BODY_MUST_NOT_LEAK" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" local_body);
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote conflicting cleanup version.");
      ignore (commit_writer env "remote cleanup conflict");
      let pending =
        check_error "cleanup conflict pending" "publish_conflict" (run env)
      in
      let original = Option.get pending.commit in
      let state_directory =
        Filename.concat env.clone
          (".git/refs/clamp/publish/" ^ thread_id)
      in
      let original_mode = (Unix.stat state_directory).st_perm in
      let pushes = ref 0 in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec:_ ->
              if attempt = 0 then incr pushes);
          after_preservation_proven =
            (fun ~branch:_ ~commit:_ ->
              Unix.chmod state_directory 0o500);
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> ());
          now = (fun () -> 1_787_832_000.) }
      in
      let cleanup_pending =
        Fun.protect
          ~finally:(fun () -> Unix.chmod state_directory original_mode)
          (fun () ->
            check_error "preserved cleanup pending"
              "publish_conflict_preserved_cleanup_pending"
              (run ~preserve:true ~hooks env))
      in
      let branch = Option.get cleanup_pending.branch in
      Alcotest.(check bool) "durable preservation is explicit" true
        cleanup_pending.preserved;
      Alcotest.(check bool) "cleanup obligation is explicit" true
        cleanup_pending.cleanup_pending;
      Alcotest.(check (option string)) "preserved original SHA"
        (Some original) cleanup_pending.commit;
      Alcotest.(check (option string)) "cleanup cause is stable"
        (Some "publish_state_update_failed") cleanup_pending.cleanup_cause;
      Alcotest.(check (list string)) "cleanup response paths are body-free"
        [ "knowledge/facts/same.md" ] cleanup_pending.paths;
      Alcotest.(check string) "remote conflict ref is durable" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check bool) "local state retained for retry" true
        (publication_refs env <> "");
      let expected_details =
        `Assoc
          [ ("published", `Bool false);
            ("preserved", `Bool true);
            ("cleanup_pending", `Bool true);
            ("commit", `String original);
            ("branch", `String branch);
            ( "paths",
              `List [ `String "knowledge/facts/same.md" ] );
            ("cleanup_cause", `String "publish_state_update_failed") ]
      in
      Alcotest.(check string) "exact cleanup-pending details"
        (Yojson.Safe.to_string expected_details)
        (Clamp.Publication.error_details cleanup_pending
        |> Yojson.Safe.to_string);
      Alcotest.(check bool) "cleanup details contain no local body" false
        (contains
           (Clamp.Publication.error_details cleanup_pending
           |> Yojson.Safe.to_string)
           local_body);
      let retry_hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt:_ ~refspec:_ ->
              Alcotest.fail "cleanup retry must not repush");
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> ());
          now = (fun () -> 1_787_832_000.) }
      in
      let recovered =
        check_error "preserved cleanup retry" "publish_conflict_preserved"
          (run ~preserve:true ~hooks:retry_hooks env)
      in
      Alcotest.(check int) "conflict branch pushed exactly once" 1 !pushes;
      Alcotest.(check bool) "retry retains durable preservation proof" true
        recovered.preserved;
      Alcotest.(check bool) "retry clears cleanup obligation" false
        recovered.cleanup_pending;
      Alcotest.(check (option string)) "retry retains branch"
        (Some branch) recovered.branch;
      Alcotest.(check (option string)) "retry retains original SHA"
        (Some original) recovered.commit;
      Alcotest.(check string) "retry removes local publication refs" ""
        (publication_refs env);
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
      local_change env "after-preserved-cleanup";
      let next = check_ok "publication after preserved cleanup" (run env) in
      Alcotest.(check string) "subsequent publication is durable" next.commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]))

let conflict_preservation_push_retry_cli () =
  with_environment "preservation-push-retry-cli" (fun env ->
      let local_body = "PENDING_PUSH_LOCAL_BODY_MUST_NOT_LEAK" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" local_body);
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote pending-push conflict.");
      ignore (commit_writer env "remote pending-push conflict");
      let publish_arguments preserve =
        [ "publish"; "--repo"; env.clone; "--thread-id"; thread_id ]
        @ (if preserve then [ "--preserve-conflict" ] else [])
        @ [ "--json" ]
      in
      let status, output, errors = capture_cli (publish_arguments false) in
      Alcotest.(check bool) "production CLI creates conflict state" true
        (status = Unix.WEXITED 3);
      Alcotest.(check string) "initial conflict stderr" "" errors;
      let initial = Yojson.Safe.from_string output in
      let open Yojson.Safe.Util in
      Alcotest.(check string) "initial conflict code" "publish_conflict"
        (initial |> member "code" |> to_string);
      let original =
        initial |> member "details" |> member "commit" |> to_string
      in
      let hook = Filename.concat env.bare "hooks/pre-receive" in
      write hook
        "#!/bin/sh\nwhile read old new ref; do\n  case \"$ref\" in refs/heads/conflicts/*) exit 1;; esac\ndone\nexit 0\n";
      Unix.chmod hook 0o755;
      let status, output, errors = capture_cli (publish_arguments true) in
      Alcotest.(check bool) "first preservation push rejected" true
        (status = Unix.WEXITED 5);
      Alcotest.(check string) "rejected preservation stderr" "" errors;
      let rejected = Yojson.Safe.from_string output in
      Alcotest.(check string) "rejected preservation code"
        "publish_conflict_preservation_failed"
        (rejected |> member "code" |> to_string);
      let details = rejected |> member "details" in
      Alcotest.(check bool) "pending preservation is explicit" true
        (details |> member "preservation_pending" |> to_bool);
      let branch = details |> member "branch" |> to_string in
      Alcotest.(check string) "pending original SHA" original
        (details |> member "commit" |> to_string);
      Alcotest.(check (list string)) "pending body-free paths"
        [ "knowledge/facts/same.md" ]
        (details |> member "paths" |> to_list |> List.map to_string);
      Alcotest.(check bool) "pending response excludes knowledge body" false
        (contains output local_body);
      Alcotest.(check bool) "rejected branch is authoritatively absent" false
        (git_succeeds env.bare
           [ "show-ref"; "--verify"; "refs/heads/" ^ branch ]);
      Alcotest.(check bool) "pending local state retained" true
        (publication_refs env <> "");
      Sys.remove hook;
      let status, output, errors = capture_cli (publish_arguments true) in
      Alcotest.(check bool) "same preserve command succeeds" true
        (status = Unix.WEXITED 3);
      Alcotest.(check string) "preserve retry stderr" "" errors;
      let preserved = Yojson.Safe.from_string output in
      Alcotest.(check string) "preserve retry code" "publish_conflict_preserved"
        (preserved |> member "code" |> to_string);
      let preserved_details = preserved |> member "details" in
      Alcotest.(check bool) "remote preservation proven" true
        (preserved_details |> member "preserved" |> to_bool);
      Alcotest.(check string) "retry reuses exact pending branch" branch
        (preserved_details |> member "branch" |> to_string);
      Alcotest.(check string) "retry preserves exact original" original
        (preserved_details |> member "commit" |> to_string);
      Alcotest.(check (list string)) "retry retains exact body-free paths"
        [ "knowledge/facts/same.md" ]
        (preserved_details |> member "paths" |> to_list |> List.map to_string);
      Alcotest.(check string) "remote branch contains exact original" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check string) "preserved branch retains exact knowledge" local_body
        (git_output env.bare
           [ "show"; "refs/heads/" ^ branch ^ ":knowledge/facts/same.md" ]
        |> String.split_on_char '\n' |> List.rev |> List.hd);
      Alcotest.(check string) "successful retry clears state" ""
        (publication_refs env);
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
      local_change env "after-pending-push-retry";
      let status, output, errors = capture_cli (publish_arguments false) in
      Alcotest.(check bool) "subsequent production publication is durable" true
        (status = Unix.WEXITED 6);
      Alcotest.(check string) "subsequent publication stderr" "" errors;
      let subsequent = Yojson.Safe.from_string output in
      Alcotest.(check string) "subsequent index-stale code"
        "publish_complete_index_stale"
        (subsequent |> member "code" |> to_string);
      let next = subsequent |> member "details" |> member "commit" |> to_string in
      Alcotest.(check string) "subsequent exact remote main" next
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check string) "subsequent publication clears state" ""
        (publication_refs env))

let v1_publication_state_migration () =
  let cli env preserve =
    capture_cli
      ([ "publish"; "--repo"; env.clone; "--thread-id"; thread_id ]
      @ (if preserve then [ "--preserve-conflict" ] else [])
      @ [ "--json" ])
  in
  let cli_error label expected_status expected_code (status, output, errors) =
    Alcotest.(check bool) (label ^ " status") true
      (status = Unix.WEXITED expected_status);
    Alcotest.(check string) (label ^ " stderr") "" errors;
    let json = Yojson.Safe.from_string output in
    Alcotest.(check string) (label ^ " code") expected_code
      Yojson.Safe.Util.(json |> member "code" |> to_string);
    json
  in
  with_environment "v1-genuine-conflict" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "V1 local conflict body.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "V1 remote conflict body.");
      ignore (commit_writer env "v1 remote conflict");
      let pending = check_error "create conflict state" "publish_conflict" (run env) in
      let original = Option.get pending.commit in
      let v1_body, _ = downgrade_publication_state_to_v1 env in
      ignore
        (cli env false
        |> cli_error "v1 conflict migration" 3 "publish_conflict");
      check_v1_migrated_exactly "v1 conflict migration" env v1_body;
      let preserved =
        cli env true
        |> cli_error "v1 conflict preservation" 3
             "publish_conflict_preserved"
      in
      let open Yojson.Safe.Util in
      let details = preserved |> member "details" in
      Alcotest.(check string) "v1 conflict original preserved" original
        (details |> member "commit" |> to_string);
      let branch = details |> member "branch" |> to_string in
      Alcotest.(check string) "v1 conflict remote branch exact" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check string) "v1 conflict state cleaned" ""
        (publication_refs env));
  with_environment "v1-clean-race" (fun env ->
      local_change env "v1-race-local";
      let rejection_hook = Filename.concat env.bare "hooks/pre-receive" in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec:_ ->
              if attempt = 1 then ignore (advance_writer env 1 ())
              else if attempt = 2 then begin
                write rejection_hook "#!/bin/sh\nexit 1\n";
                Unix.chmod rejection_hook 0o755
              end);
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> Alcotest.fail "failed race synced");
          now = Unix.gettimeofday }
      in
      ignore (check_error "create v1 race state" "publish_push_failed"
                (run ~hooks env));
      Sys.remove rejection_hook;
      let v1_body, _ = downgrade_publication_state_to_v1 env in
      ignore
        (cli env true
        |> cli_error "v1 race migration remains recoverable" 2
             "publish_no_active_conflict");
      check_v1_migrated_exactly "v1 race migration" env v1_body;
      let resumed =
        cli env false
        |> cli_error "v1 race resume" 6 "publish_complete_index_stale"
      in
      let commit =
        Yojson.Safe.Util.(resumed |> member "details" |> member "commit" |> to_string)
      in
      Alcotest.(check string) "v1 race resume exact remote main" commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check string) "v1 race state cleaned" ""
        (publication_refs env));
  with_environment "v1-durable-main-cleanup" (fun env ->
      local_change env "v1-durable-main";
      let state_directory =
        Filename.concat env.clone
          (".git/refs/clamp/publish/" ^ thread_id)
      in
      let mode = ref None in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt:_ ~refspec:_ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push =
            (fun ~commit:_ ->
              mode := Some (Unix.stat state_directory).st_perm;
              Unix.chmod state_directory 0o500);
          before_sync =
            (fun ~commit:_ -> Option.iter (Unix.chmod state_directory) !mode);
          now = Unix.gettimeofday }
      in
      let pending =
        check_error "create v1 durable-main cleanup state"
          "publish_complete_cleanup_failed" (run ~hooks env)
      in
      let published = Option.get pending.commit in
      let v1_body, _ = downgrade_publication_state_to_v1 env in
      ignore
        (cli env true
        |> cli_error "v1 durable-main migration remains recoverable" 2
             "publish_no_active_conflict");
      check_v1_migrated_exactly "v1 durable-main migration" env v1_body;
      let resumed =
        cli env false
        |> cli_error "v1 durable-main resume" 6
             "publish_complete_index_stale"
      in
      Alcotest.(check string) "v1 durable-main SHA retained" published
        Yojson.Safe.Util.(resumed |> member "details" |> member "commit" |> to_string);
      Alcotest.(check string) "v1 durable-main state cleaned" ""
        (publication_refs env));
  with_environment "v1-atomic-migration" (fun env ->
      local_change env "v1-atomic";
      let hook = Filename.concat env.bare "hooks/pre-receive" in
      write hook "#!/bin/sh\nexit 1\n";
      Unix.chmod hook 0o755;
      ignore
        (check_error "create v1 atomic state" "publish_push_failed" (run env));
      Sys.remove hook;
      let _, v1_object = downgrade_publication_state_to_v1 env in
      let original =
        git_output env.clone [ "rev-parse"; publication_original_ref ]
      in
      let state_directory = Filename.dirname (Filename.concat env.clone ".git/x")
        |> fun git_dir ->
        Filename.concat git_dir ("refs/clamp/publish/" ^ thread_id)
      in
      let original_mode = (Unix.stat state_directory).st_perm in
      let failure =
        Fun.protect
          ~finally:(fun () -> Unix.chmod state_directory original_mode)
          (fun () ->
            Unix.chmod state_directory 0o500;
            cli env false
            |> cli_error "v1 atomic migration failure" 70
                 "publish_state_update_failed")
      in
      ignore failure;
      Alcotest.(check string) "failed migration retains exact v1 state ref"
        v1_object (git_output env.clone [ "rev-parse"; publication_state_ref ]);
      Alcotest.(check string) "failed migration retains exact original ref"
        original (git_output env.clone [ "rev-parse"; publication_original_ref ]);
      Alcotest.(check bool) "failed migration retains v1 body" true
        (String.starts_with ~prefix:"clamp-publish-state-v1\000"
           (publication_state_body env));
      ignore
        (cli env false
        |> cli_error "v1 atomic migration retry" 6
             "publish_complete_index_stale");
      Alcotest.(check string) "migration retry clears state" ""
        (publication_refs env))

let v1_post_abort_conflict_recovery () =
  let cli env preserve =
    capture_cli
      ([ "publish"; "--repo"; env.clone; "--thread-id"; thread_id ]
      @ (if preserve then [ "--preserve-conflict" ] else [])
      @ [ "--json" ])
  in
  let cli_error label expected_status expected_code (status, output, errors) =
    Alcotest.(check bool) (label ^ " status") true
      (status = Unix.WEXITED expected_status);
    Alcotest.(check string) (label ^ " stderr") "" errors;
    let json = Yojson.Safe.from_string output in
    Alcotest.(check string) (label ^ " code") expected_code
      Yojson.Safe.Util.(json |> member "code" |> to_string);
    json
  in
  with_environment "v1-post-abort" (fun env ->
      let local_body = "V1_POST_ABORT_LOCAL_BODY_MUST_NOT_LEAK" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" local_body);
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "V1 post-abort remote conflict.");
      ignore (commit_writer env "v1 post-abort remote conflict");
      let pending =
        check_error "create v1 post-abort conflict" "publish_conflict" (run env)
      in
      let original = Option.get pending.commit in
      git env.clone
        [ "-c"; "core.hooksPath=/dev/null"; "rebase"; "--abort" ];
      git env.clone [ "switch"; "--quiet"; "main" ];
      Alcotest.(check string) "post-abort HEAD is exact original" original
        (git_output env.clone [ "rev-parse"; "HEAD" ]);
      let v1_body, v1_object = downgrade_publication_state_to_v1 env in
      let state_directory =
        Filename.concat env.clone
          (".git/refs/clamp/publish/" ^ thread_id)
      in
      let original_mode = (Unix.stat state_directory).st_perm in
      let migration_failure =
        Fun.protect
          ~finally:(fun () -> Unix.chmod state_directory original_mode)
          (fun () ->
            Unix.chmod state_directory 0o500;
            cli env true
            |> cli_error "post-abort migration failure" 70
                 "publish_state_update_failed")
      in
      ignore migration_failure;
      Alcotest.(check string) "migration failure retains exact v1 ref" v1_object
        (git_output env.clone [ "rev-parse"; publication_state_ref ]);
      Alcotest.(check string) "migration failure retains exact v1 body" v1_body
        (publication_state_body env);
      let required =
        cli env false
        |> cli_error "post-abort explicit recovery required" 2
             "publish_conflict_post_abort_preservation_required"
      in
      let open Yojson.Safe.Util in
      let required_details = required |> member "details" in
      Alcotest.(check string) "post-abort result retains original" original
        (required_details |> member "commit" |> to_string);
      Alcotest.(check (list string)) "post-abort result is body-free"
        [ "knowledge/facts/same.md" ]
        (required_details |> member "paths" |> to_list |> List.map to_string);
      Alcotest.(check bool) "post-abort result excludes body" false
        (contains (Yojson.Safe.to_string required) local_body);
      let migrated_object =
        git_output env.clone [ "rev-parse"; publication_state_ref ]
      in
      Alcotest.(check bool) "post-abort migration is explicit" true
        (String.starts_with
           ~prefix:"clamp-publish-state-v3\0000\000legacy_unresolved\000"
           (publication_state_body env));
      write (Filename.concat env.clone "README.fixture") "owner work retained\n";
      let unverified =
        cli env true
        |> cli_error "post-abort owner work fails closed" 2
             "publish_conflict_post_abort_unverified"
      in
      Alcotest.(check string) "post-abort owner cause" "worktree_changed"
        (unverified |> member "details" |> member "cause" |> to_string);
      Alcotest.(check string) "owner work is not discarded" "owner work retained\n"
        (read (Filename.concat env.clone "README.fixture"));
      Alcotest.(check string) "unverified state ref retained" migrated_object
        (git_output env.clone [ "rev-parse"; publication_state_ref ]);
      write (Filename.concat env.clone "README.fixture") "fixture\n";
      let allocation_failure =
        Fun.protect
          ~finally:(fun () -> Unix.chmod state_directory original_mode)
          (fun () ->
            Unix.chmod state_directory 0o500;
            cli env true
            |> cli_error "post-abort allocation failure" 70
                 "publish_conflict_preservation_allocation_failed")
      in
      Alcotest.(check string) "allocation failure cause"
        "publish_state_update_failed"
        (allocation_failure |> member "details" |> member "cause" |> to_string);
      Alcotest.(check string) "allocation failure retains exact state"
        migrated_object
        (git_output env.clone [ "rev-parse"; publication_state_ref ]);
      let hook = Filename.concat env.bare "hooks/pre-receive" in
      write hook
        "#!/bin/sh\nwhile read old new ref; do\n  case \"$ref\" in refs/heads/conflicts/*) exit 1;; esac\ndone\nexit 0\n";
      Unix.chmod hook 0o755;
      let push_failure =
        cli env true
        |> cli_error "post-abort first push failure" 5
             "publish_conflict_preservation_failed"
      in
      let push_details = push_failure |> member "details" in
      let branch = push_details |> member "branch" |> to_string in
      Alcotest.(check bool) "post-abort push is explicitly pending" true
        (push_details |> member "preservation_pending" |> to_bool);
      Alcotest.(check string) "post-abort pending original" original
        (push_details |> member "commit" |> to_string);
      Alcotest.(check (list string)) "post-abort pending paths stay body-free"
        [ "knowledge/facts/same.md" ]
        (push_details |> member "paths" |> to_list |> List.map to_string);
      Alcotest.(check bool) "push failure records pending state" true
        (String.starts_with
           ~prefix:
             ("clamp-publish-state-v3\0000\000push_pending\000" ^ branch
            ^ "\000")
           (publication_state_body env));
      Alcotest.(check string) "push failure retains exact original ref" original
        (git_output env.clone [ "rev-parse"; publication_original_ref ]);
      Alcotest.(check bool) "failed push leaves exact branch absent" false
        (git_succeeds env.bare
           [ "show-ref"; "--verify"; "refs/heads/" ^ branch ]);
      Alcotest.(check bool) "push failure response excludes body" false
        (contains (Yojson.Safe.to_string push_failure) local_body);
      Sys.remove hook;
      let preserved =
        cli env true
        |> cli_error "post-abort exact push retry" 3
             "publish_conflict_preserved"
      in
      let preserved_details = preserved |> member "details" in
      Alcotest.(check string) "post-abort retry reuses branch" branch
        (preserved_details |> member "branch" |> to_string);
      Alcotest.(check string) "post-abort remote has exact original" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      Alcotest.(check string) "post-abort state cleaned" ""
        (publication_refs env);
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
      local_change env "after-v1-post-abort";
      let next =
        cli env false
        |> cli_error "publication after v1 post-abort recovery" 6
             "publish_complete_index_stale"
      in
      let next_commit = next |> member "details" |> member "commit" |> to_string in
      Alcotest.(check string) "later publication is durable" next_commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]))

let v2_preservation_conservatism () =
  with_environment "v2-pending-absent" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "V2 pending local conflict.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "V2 pending remote conflict.");
      ignore (commit_writer env "v2 pending conflict");
      let pending = check_error "v2 pending conflict" "publish_conflict" (run env) in
      let original = Option.get pending.commit in
      let hook = Filename.concat env.bare "hooks/pre-receive" in
      write hook
        "#!/bin/sh\nwhile read old new ref; do\n  case \"$ref\" in refs/heads/conflicts/*) exit 1;; esac\ndone\nexit 0\n";
      Unix.chmod hook 0o755;
      let rejected =
        check_error "v2 pending first push"
          "publish_conflict_preservation_failed" (run ~preserve:true env)
      in
      let branch = Option.get rejected.branch in
      ignore (downgrade_publication_state_to_v2 env);
      Alcotest.(check bool) "v2 records the pending branch" true
        (contains (publication_state_body env) branch);
      Sys.remove hook;
      let pushes = ref 0 in
      let hooks =
        { Clamp.Publication.For_test.default_hooks with
          before_push =
            (fun ~attempt:_ ~refspec:_ -> incr pushes) }
      in
      let preserved =
        check_error "v2 absent branch retry" "publish_conflict_preserved"
          (run ~preserve:true ~hooks env)
      in
      Alcotest.(check int) "v2 absent branch performs one safe push" 1 !pushes;
      Alcotest.(check (option string)) "v2 pending branch reused" (Some branch)
        preserved.branch;
      Alcotest.(check string) "v2 pending exact original is durable" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]));
  with_environment "v2-remote-proven" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "V2 remotely proven local conflict.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "V2 remotely proven remote conflict.");
      ignore (commit_writer env "v2 remotely proven conflict");
      let pending =
        check_error "v2 proven conflict" "publish_conflict" (run env)
      in
      let original = Option.get pending.commit in
      let state_directory =
        Filename.concat env.clone
          (".git/refs/clamp/publish/" ^ thread_id)
      in
      let original_mode = ref None in
      let hooks =
        { Clamp.Publication.For_test.default_hooks with
          after_preservation_proven =
            (fun ~branch:_ ~commit:_ ->
              original_mode := Some (Unix.stat state_directory).st_perm;
              Unix.chmod state_directory 0o500) }
      in
      let cleanup_pending =
        Fun.protect
          ~finally:(fun () ->
            Option.iter (Unix.chmod state_directory) !original_mode)
          (fun () ->
            check_error "v2 proven cleanup pending"
              "publish_conflict_preserved_cleanup_pending"
              (run ~preserve:true ~hooks env))
      in
      let branch = Option.get cleanup_pending.branch in
      Alcotest.(check string) "v2 proven remote exact original" original
        (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
      ignore (downgrade_publication_state_to_v2 env);
      let no_push_hooks =
        { Clamp.Publication.For_test.default_hooks with
          before_push =
            (fun ~attempt:_ ~refspec:_ ->
              Alcotest.fail "v2 remote proof must prevent a repush") }
      in
      let recovered =
        check_error "v2 remote proof retry" "publish_conflict_preserved"
          (run ~preserve:true ~hooks:no_push_hooks env)
      in
      Alcotest.(check (option string)) "v2 proof retains branch" (Some branch)
        recovered.branch;
      Alcotest.(check string) "v2 proof cleanup removes local state" ""
        (publication_refs env))

let reviewed_phase7_cli_cross_version () =
  match Sys.getenv_opt "CLAMP_REVIEWED_PHASE7_KB" with
  | None ->
      Alcotest.skip ()
  | Some binary ->
      Alcotest.(check bool) "reviewed Phase 7 CLI exists" true
        (Sys.file_exists binary);
      let arguments env preserve =
        [ "publish"; "--repo"; env.clone; "--thread-id"; thread_id ]
        @ (if preserve then [ "--preserve-conflict" ] else [])
        @ [ "--json" ]
      in
      let invoke label expected_status expected_code capture =
        let status, output, errors = capture in
        Alcotest.(check bool) (label ^ " status") true
          (status = Unix.WEXITED expected_status);
        Alcotest.(check string) (label ^ " stderr") "" errors;
        let json = Yojson.Safe.from_string output in
        Alcotest.(check string) (label ^ " code") expected_code
          Yojson.Safe.Util.(json |> member "code" |> to_string);
        json
      in
      let old env preserve = capture_binary binary (arguments env preserve)
      and final env preserve = capture_cli (arguments env preserve) in
      with_environment "reviewed-v1-cli-conflict" (fun env ->
          write (Filename.concat env.clone "knowledge/facts/same.md")
            (fact "Same" "Reviewed Phase 7 CLI local conflict.");
          write (Filename.concat env.writer "knowledge/facts/same.md")
            (fact "Same" "Reviewed Phase 7 CLI remote conflict.");
          ignore (commit_writer env "reviewed v1 conflict");
          let pending =
            old env false |> invoke "reviewed v1 conflict" 3 "publish_conflict"
          in
          Alcotest.(check bool) "reviewed CLI wrote v1 conflict state" true
            (String.starts_with ~prefix:"clamp-publish-state-v1\000"
               (publication_state_body env));
          let original =
            Yojson.Safe.Util.(pending |> member "details" |> member "commit" |> to_string)
          in
          let preserved =
            final env true
            |> invoke "final CLI preserves reviewed v1 conflict" 3
                 "publish_conflict_preserved"
          in
          let branch =
            Yojson.Safe.Util.(preserved |> member "details" |> member "branch" |> to_string)
          in
          Alcotest.(check string) "reviewed v1 conflict exact remote SHA" original
            (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
          Alcotest.(check string) "reviewed v1 conflict state cleaned" ""
            (publication_refs env));
      with_environment "reviewed-v1-cli-post-abort" (fun env ->
          let local_body = "REVIEWED_V1_POST_ABORT_BODY" in
          write (Filename.concat env.clone "knowledge/facts/same.md")
            (fact "Same" local_body);
          write (Filename.concat env.writer "knowledge/facts/same.md")
            (fact "Same" "Reviewed Phase 7 post-abort remote conflict.");
          ignore (commit_writer env "reviewed v1 post-abort conflict");
          let pending =
            old env false
            |> invoke "reviewed v1 post-abort conflict" 3 "publish_conflict"
          in
          let original =
            Yojson.Safe.Util.(pending |> member "details" |> member "commit" |> to_string)
          in
          let state_directory =
            Filename.concat env.clone
              (".git/refs/clamp/publish/" ^ thread_id)
          and hook = Filename.concat env.bare "hooks/pre-receive" in
          write hook
            (Printf.sprintf
               "#!/bin/sh\nwhile read old new ref; do\n  case \"$ref\" in refs/heads/conflicts/*) chmod 500 %s;; esac\ndone\nexit 0\n"
               (Filename.quote state_directory));
          Unix.chmod hook 0o755;
          let legacy =
            Fun.protect
              ~finally:(fun () ->
                if Sys.file_exists state_directory then
                  Unix.chmod state_directory 0o755;
                if Sys.file_exists hook then Sys.remove hook)
              (fun () ->
                old env true
                |> invoke "reviewed v1 post-abort cleanup failure" 3
                     "publish_conflict_preserved")
          in
          let legacy_branch =
            Yojson.Safe.Util.(legacy |> member "details" |> member "branch" |> to_string)
          in
          Alcotest.(check string) "legacy preservation is remotely durable" original
            (git_output env.bare [ "rev-parse"; "refs/heads/" ^ legacy_branch ]);
          Alcotest.(check bool) "reviewed post-abort state remains v1" true
            (String.starts_with ~prefix:"clamp-publish-state-v1\000"
               (publication_state_body env));
          Alcotest.(check bool) "reviewed post-abort has no active rebase" false
            (git_succeeds env.clone [ "rev-parse"; "--verify"; "REBASE_HEAD" ]);
          Unix.sleep 1;
          let recovered =
            final env true
            |> invoke "final CLI recovers reviewed v1 post-abort state" 3
                 "publish_conflict_preserved"
          in
          let details = Yojson.Safe.Util.(recovered |> member "details") in
          let branch = Yojson.Safe.Util.(details |> member "branch" |> to_string) in
          Alcotest.(check string) "post-abort recovery preserves exact original"
            original Yojson.Safe.Util.(details |> member "commit" |> to_string);
          Alcotest.(check (list string)) "post-abort recovery exact paths"
            [ "knowledge/facts/same.md" ]
            Yojson.Safe.Util.(details |> member "paths" |> to_list |> List.map to_string);
          Alcotest.(check string) "post-abort recovery remote exact SHA" original
            (git_output env.bare [ "rev-parse"; "refs/heads/" ^ branch ]);
          Alcotest.(check string) "post-abort recovery retains knowledge" local_body
            (git_output env.bare
               [ "show"; "refs/heads/" ^ branch ^ ":knowledge/facts/same.md" ]
            |> String.split_on_char '\n' |> List.rev |> List.hd);
          Alcotest.(check string) "post-abort recovery cleans state" ""
            (publication_refs env);
          git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
          git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
          local_change env "after-reviewed-v1-post-abort";
          let later =
            final env false
            |> invoke "publication after reviewed v1 post-abort" 6
                 "publish_complete_index_stale"
          in
          let later_commit =
            Yojson.Safe.Util.(later |> member "details" |> member "commit" |> to_string)
          in
          Alcotest.(check string) "post-abort later publication durable"
            later_commit (git_output env.bare [ "rev-parse"; "refs/heads/main" ]));
      with_environment "reviewed-v1-cli-clean" (fun env ->
          local_change env "reviewed-v1-clean";
          let hook = Filename.concat env.bare "hooks/pre-receive" in
          write hook "#!/bin/sh\nexit 1\n";
          Unix.chmod hook 0o755;
          ignore
            (old env false
            |> invoke "reviewed v1 clean retained state" 5
                 "publish_push_failed");
          Alcotest.(check bool) "reviewed CLI wrote v1 clean state" true
            (String.starts_with ~prefix:"clamp-publish-state-v1\000"
               (publication_state_body env));
          Sys.remove hook;
          let resumed =
            final env false
            |> invoke "final CLI resumes reviewed v1 clean state" 6
                 "publish_complete_index_stale"
          in
          let commit =
            Yojson.Safe.Util.(resumed |> member "details" |> member "commit" |> to_string)
          in
          Alcotest.(check string) "reviewed v1 clean exact remote main" commit
            (git_output env.bare [ "rev-parse"; "refs/heads/main" ]));
      with_environment "reviewed-v1-cli-durable" (fun env ->
          local_change env "reviewed-v1-durable";
          let state_directory =
            Filename.concat env.clone
              (".git/refs/clamp/publish/" ^ thread_id)
          and hook = Filename.concat env.bare "hooks/pre-receive" in
          write hook
            (Printf.sprintf
               "#!/bin/sh\nwhile read old new ref; do\n  if [ \"$ref\" = refs/heads/main ]; then chmod 500 %s; fi\ndone\nexit 0\n"
               (Filename.quote state_directory));
          Unix.chmod hook 0o755;
          let pending =
            Fun.protect
              ~finally:(fun () ->
                if Sys.file_exists state_directory then
                  Unix.chmod state_directory 0o755;
                if Sys.file_exists hook then Sys.remove hook)
              (fun () ->
                old env false
                |> invoke "reviewed v1 durable cleanup state" 6
                     "publish_complete_index_stale_cleanup_pending")
          in
          let published =
            Yojson.Safe.Util.(pending |> member "details" |> member "commit" |> to_string)
          in
          Alcotest.(check bool) "reviewed CLI wrote v1 durable state" true
            (String.starts_with ~prefix:"clamp-publish-state-v1\000"
               (publication_state_body env));
          let resumed =
            final env false
            |> invoke "final CLI resumes reviewed v1 durable state" 6
                 "publish_complete_index_stale"
          in
          Alcotest.(check string) "reviewed v1 durable exact SHA" published
            Yojson.Safe.Util.(resumed |> member "details" |> member "commit" |> to_string);
          Alcotest.(check string) "reviewed v1 durable state cleaned" ""
            (publication_refs env))

let conflict_owner_safety () =
  with_environment "conflict-owner-work" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Original local owner-safe version.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote conflicting version.");
      ignore (commit_writer env "remote owner-safe conflict");
      let pending = check_error "owner-safe pending" "publish_conflict" (run env) in
      write (Filename.concat env.clone "README.fixture") "owner work preserved\n";
      let refused =
        check_error "owner work refusal" "publish_unrelated_changes"
          (run ~preserve:true env)
      in
      Alcotest.(check (list string)) "unrelated owner path reported"
        [ "README.fixture" ] refused.paths;
      Alcotest.(check string) "unrelated owner bytes preserved"
        "owner work preserved\n"
        (read (Filename.concat env.clone "README.fixture"));
      Alcotest.(check (list string)) "original conflict paths retained"
        [ "knowledge/facts/same.md" ] pending.paths;
      write (Filename.concat env.clone "README.fixture") "fixture\n";
      ignore
        (check_error "preserve after owner work restored"
           "publish_conflict_preserved" (run ~preserve:true env)));
  with_environment "staged-resolution-preserve" (fun env ->
      let original = fact "Same" "Original staged-fallback version." in
      write (Filename.concat env.clone "knowledge/facts/same.md") original;
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote staged-fallback version.");
      ignore (commit_writer env "remote staged fallback conflict");
      let pending =
        check_error "staged fallback pending" "publish_conflict" (run env)
      in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Attempted staged semantic resolution.");
      git env.clone [ "add"; "--"; "knowledge/facts/same.md" ];
      let preserved =
        check_error "staged resolution fallback" "publish_conflict_preserved"
          (run ~preserve:true env)
      in
      Alcotest.(check (list string)) "persisted original path set"
        pending.paths preserved.paths;
      Alcotest.(check string) "preserved original, not attempted resolution"
        original
        (git_output_raw env.bare
           [ "show"; "refs/heads/" ^ Option.get preserved.branch
             ^ ":knowledge/facts/same.md" ]));
  with_environment "original-conflict-set" (fun env ->
      let other = "knowledge/facts/other-conflict.md" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Local first conflict.");
      write (Filename.concat env.clone other)
        (fact "Other conflict" "Local second conflict.");
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote first conflict.");
      write (Filename.concat env.writer other)
        (fact "Other conflict" "Remote second conflict.");
      ignore (commit_writer env "two remote conflicts");
      let expected =
        [ "knowledge/facts/other-conflict.md"; "knowledge/facts/same.md" ]
      in
      let pending = check_error "two conflicts" "publish_conflict" (run env) in
      Alcotest.(check (list string)) "initial genuine path set" expected
        pending.paths;
      write (Filename.concat env.clone other)
        (fact "Other conflict" "One path resolved.");
      git env.clone [ "add"; "--"; other ];
      let partial =
        check_error "partially resolved conflict" "publish_conflict" (run env)
      in
      Alcotest.(check (list string)) "original path set survives partial resolution"
        expected partial.paths;
      let preserved =
        check_error "partial resolution preservation" "publish_conflict_preserved"
          (run ~preserve:true env)
      in
      Alcotest.(check (list string)) "preservation returns original path set"
        expected preserved.paths)

let conflicts_do_not_consume_clean_races () =
  with_environment "conflict-race-accounting" (fun env ->
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" "Initial local version.");
      let calls = ref 0 and attempts = ref [] in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt ~refspec:_ ->
              incr calls;
              attempts := attempt :: !attempts;
              match !calls with
              | 1 -> ignore (advance_writer env 1 ~same:true ())
              | 2 -> ignore (advance_writer env 2 ())
              | 3 -> ignore (advance_writer env 3 ())
              | 4 -> ignore (advance_writer env 4 ())
              | _ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync = (fun ~commit:_ -> Alcotest.fail "recovery must not sync");
          now = (fun () -> 1_787_733_723.) }
      in
      ignore
        (check_error "interleaved genuine conflict" "publish_conflict"
           (run ~hooks env));
      let resolved = fact "Same" "Exact interleaved semantic resolution." in
      write (Filename.concat env.clone "knowledge/facts/same.md") resolved;
      git env.clone [ "add"; "--"; "knowledge/facts/same.md" ];
      let exhausted =
        check_error "three clean races after conflict" "publish_race_exhausted"
          (run ~hooks env)
      in
      Alcotest.(check (list int)) "conflict did not consume clean slot"
        [ 1; 1; 2; 3; 4 ] (List.rev !attempts);
      let commit = Option.get exhausted.commit in
      Alcotest.(check string) "resolved bytes retained through recovery"
        resolved
        (git_output_raw env.bare
           [ "show"; commit ^ ":knowledge/facts/same.md" ]);
      List.iter
        (fun index ->
          ignore
            (git_output env.bare
               [ "show";
                 Printf.sprintf "%s:knowledge/facts/winner-%d.md" commit index ]))
        [ 2; 3; 4 ];
      Alcotest.(check string) "interleaved recovery state cleaned" ""
        (publication_refs env))

let safety_refusals () =
  let case label expected prepare =
    with_environment label (fun env ->
        local_change env "pending";
        prepare env;
        ignore (check_error label expected (run env)))
  in
  case "staged" "publish_unrelated_changes"
    (fun env ->
      write (Filename.concat env.clone "README.fixture") "staged\n";
      git env.clone [ "add"; "README.fixture" ]);
  case "worktree" "publish_unrelated_changes"
    (fun env -> write (Filename.concat env.clone "README.fixture") "dirty\n");
  case "untracked" "publish_unrelated_changes"
    (fun env -> write (Filename.concat env.clone "unmanaged.tmp") "dirty\n");
  case "ahead-history" "publish_unpublished_commits"
    (fun env ->
      git env.clone [ "add"; "knowledge/facts/pending.md" ];
      git env.clone [ "commit"; "--quiet"; "-m"; "pre-existing" ];
      let head = git_output env.clone [ "rev-parse"; "HEAD" ]
      and tracked =
        git_output env.clone [ "rev-parse"; "refs/remotes/origin/main" ]
      in
      Alcotest.(check bool) "ahead history is not behind" false
        (git_succeeds env.clone
           [ "merge-base"; "--is-ancestor"; head; tracked ]);
      Alcotest.(check bool) "tracking ref is ancestor of ahead history" true
        (git_succeeds env.clone
           [ "merge-base"; "--is-ancestor"; tracked; head ]);
      local_change env "second");
  with_environment "diverged-history" (fun env ->
      local_change env "local-commit";
      git env.clone [ "add"; "knowledge/facts/local-commit.md" ];
      git env.clone [ "commit"; "--quiet"; "-m"; "local divergence" ];
      ignore (advance_writer env 8 ());
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      let head = git_output env.clone [ "rev-parse"; "HEAD" ]
      and tracked =
        git_output env.clone [ "rev-parse"; "refs/remotes/origin/main" ]
      in
      Alcotest.(check bool) "diverged head is not tracking ancestor" false
        (git_succeeds env.clone
           [ "merge-base"; "--is-ancestor"; head; tracked ]);
      Alcotest.(check bool) "diverged tracking is not head ancestor" false
        (git_succeeds env.clone
           [ "merge-base"; "--is-ancestor"; tracked; head ]);
      local_change env "diverged-pending";
      ignore
        (check_error "diverged history" "publish_unpublished_commits"
           (run env)));
  case "wrong-branch" "publish_ref_invalid"
    (fun env -> git env.clone [ "switch"; "--quiet"; "-c"; "other" ]);
  case "detached" "publish_ref_invalid"
    (fun env -> git env.clone [ "checkout"; "--quiet"; "--detach" ]);
  case "author" "publish_author_missing"
    (fun env -> git env.clone [ "config"; "--unset"; "user.email" ]);
  case "ambiguous-author" "git_config_invalid"
    (fun env -> git env.clone [ "config"; "--add"; "user.email"; "other@local.invalid" ]);
  with_environment "remote" (fun env ->
      local_change env "pending";
      let other = Filename.concat env.root "other.git" in
      command "/usr/bin/git"
        [ "init"; "--quiet"; "--bare"; "--initial-branch=main"; other ];
      git env.clone [ "remote"; "set-url"; "--push"; "origin"; other ];
      ignore (check_error "wrong remote" "publish_remote_invalid" (run env)));
  with_environment "thread" (fun env ->
      local_change env "pending";
      let result =
        Clamp.Publication.For_test.run ~repo:env.clone ~thread_id:"not-a-thread"
          ~preserve_conflict:false ~sync:successful_sync
          ~hooks:Clamp.Publication.For_test.default_hooks
      in
      ignore (check_error "thread" "publish_thread_id_invalid" result));
  with_environment "non-force-fetch" (fun env ->
      let advanced = advance_writer env 1 () in
      git env.clone [ "fetch"; "--quiet"; "origin"; "main" ];
      git env.clone [ "reset"; "--quiet"; "--hard"; "origin/main" ];
      let parent = git_output env.writer [ "rev-parse"; advanced ^ "^" ] in
      git env.bare [ "update-ref"; "refs/heads/main"; parent; advanced ];
      local_change env "pending";
      ignore (check_error "non-force fetch" "git_failed" (run env)))

let push_failure_and_stale_index () =
  with_environment "push-failure" (fun env ->
      local_change env "pending";
      let hook = Filename.concat env.bare "hooks/pre-receive" in
      write hook "#!/bin/sh\nexit 1\n";
      Unix.chmod hook 0o755;
      ignore (check_error "push failure" "publish_push_failed" (run env)));
  with_environment "sync-failure" (fun env ->
      local_change env "durable";
      let sync _ =
        Error
          { Clamp.Sync.kind = Transient; code = "fixture_index_failed";
            message = "Index unavailable."; diagnostics = [] }
      in
      let error =
        check_error "stale index" "publish_complete_index_stale"
          (run ~sync env)
      in
      Alcotest.(check bool) "push remains successful" true error.published;
      Alcotest.(check string) "durable exact commit" (Option.get error.commit)
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]));
  with_environment "advanced-tip" (fun env ->
      local_change env "published";
      let pushed = ref None in
      let hooks =
        { Clamp.Publication.For_test.before_push = (fun ~attempt:_ ~refspec:_ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push = (fun ~commit:_ -> ());
          before_sync =
            (fun ~commit -> pushed := Some commit; ignore (advance_writer env 9 ()));
          now = Unix.gettimeofday }
      in
      let sync commit =
        if git_output env.bare [ "rev-parse"; "refs/heads/main" ] = commit then
          successful_sync commit
        else
          Error
            { Clamp.Sync.kind = Validation; code = "sync_target_mismatch";
              message = "Target advanced."; diagnostics = [] }
      in
      let error =
        check_error "advanced stale" "publish_complete_index_stale"
          (run ~hooks ~sync env)
      in
      Alcotest.(check bool) "advanced push still published" true error.published;
      Alcotest.(check (option string)) "reported pushed SHA" !pushed error.commit;
      Alcotest.(check (option string)) "stale cause"
        (Some "sync_target_mismatch") error.cause)

let state_atomicity_and_cleanup () =
  with_environment "interrupted-after-push" (fun env ->
      local_change env "interrupted";
      let pushed = ref None in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt:_ ~refspec:_ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push =
            (fun ~commit ->
              pushed := Some commit;
              raise (Failure "simulated process interruption"));
          before_sync = (fun ~commit:_ -> Alcotest.fail "interruption synced");
          now = Unix.gettimeofday }
      in
      ignore (check_error "simulated interruption" "write_failed" (run ~hooks env));
      let pushed = Option.get !pushed in
      Alcotest.(check string) "interrupted push is durable" pushed
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check bool) "interrupted state retained" true
        (publication_refs env <> "");
      let resumed = check_ok "already-remote resume" (run env) in
      Alcotest.(check string) "already-remote exact commit" pushed resumed.commit;
      Alcotest.(check string) "already-remote state cleaned" ""
        (publication_refs env));
  with_environment "cleanup-failure" (fun env ->
      local_change env "cleanup";
      let pushed = ref None in
      let original_ref =
        "refs/clamp/publish/" ^ thread_id ^ "/original"
      in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt:_ ~refspec:_ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push =
            (fun ~commit ->
              pushed := Some commit;
              git env.clone [ "update-ref"; "-d"; original_ref ]);
          before_sync = (fun ~commit:_ -> ());
          now = Unix.gettimeofday }
      in
      let error =
        check_error "published cleanup failure" "publish_complete_cleanup_failed"
          (run ~hooks env)
      in
      Alcotest.(check bool) "cleanup failure remains published" true
        error.published;
      Alcotest.(check (option string)) "cleanup exact published SHA" !pushed
        error.commit;
      Alcotest.(check string) "cleanup-failed main is durable"
        (Option.get !pushed)
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check bool) "failed cleanup not ignored" true
        (publication_refs env <> "");
      git env.clone
        [ "update-ref"; "-d";
          "refs/clamp/publish/" ^ thread_id ^ "/state" ]);
  with_environment "cleanup-and-sync-failure" (fun env ->
      local_change env "combined-failure";
      let pushed = ref None in
      let state_directory =
        Filename.concat env.clone
          (".git/refs/clamp/publish/" ^ thread_id)
      in
      let original_mode = ref None in
      let restore_state_directory () =
        Option.iter (Unix.chmod state_directory) !original_mode
      in
      let hooks =
        { Clamp.Publication.For_test.before_push =
            (fun ~attempt:_ ~refspec:_ -> ());
          after_preservation_proven = (fun ~branch:_ ~commit:_ -> ());
          after_main_push =
            (fun ~commit ->
              pushed := Some commit;
              original_mode := Some (Unix.stat state_directory).st_perm;
              Unix.chmod state_directory 0o500);
          before_sync = (fun ~commit:_ -> restore_state_directory ());
          now = Unix.gettimeofday }
      in
      let diagnostic =
        Clamp.Diagnostic.make ~field:"checkpoint" "knowledge"
          "fixture_sync_diagnostic" "Fixture index diagnostic."
      in
      let sync _ =
        Error
          { Clamp.Sync.kind = Transient; code = "fixture_index_failed";
            message = "Index unavailable."; diagnostics = [ diagnostic ] }
      in
      let error =
        Fun.protect ~finally:restore_state_directory (fun () ->
            check_error "combined durable failure"
              "publish_complete_index_stale_cleanup_pending"
              (run ~hooks ~sync env))
      in
      let pushed = Option.get !pushed in
      let message =
        "Git publication succeeded, but the derived index is stale and local publication-state cleanup is incomplete; synchronize the index later and retry or repair local cleanup before another publication."
      in
      Alcotest.(check string) "combined stable message" message error.message;
      Alcotest.(check int) "combined stale exit class" 6
        (Clamp.Publication.exit_class error |> Clamp.Exit_class.code);
      Alcotest.(check bool) "combined result remains published" true
        error.published;
      Alcotest.(check (option string)) "combined exact published SHA"
        (Some pushed) error.commit;
      Alcotest.(check string) "combined main is durable" pushed
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      Alcotest.(check (option string)) "combined sync cause"
        (Some "fixture_index_failed") error.cause;
      Alcotest.(check (option string)) "combined cleanup cause"
        (Some "publish_state_update_failed") error.cleanup_cause;
      Alcotest.(check bool) "combined refs retained" true
        (publication_refs env <> "");
      let expected_details =
        `Assoc
          [ ("published", `Bool true);
            ("commit", `String pushed);
            ("cause", `String "fixture_index_failed");
            ("cleanup_cause", `String "publish_state_update_failed");
            ("diagnostics", `List [ Clamp.Diagnostic.json diagnostic ]) ]
      in
      Alcotest.(check string) "combined exact JSON details"
        (Yojson.Safe.to_string expected_details)
        (Clamp.Publication.error_details error |> Yojson.Safe.to_string);
      let envelope =
        Clamp.Cli_result.failure
          ~exit_class:(Clamp.Publication.exit_class error) ~code:error.code
          ~message:error.message ~details:(Clamp.Publication.error_details error)
      in
      let expected_envelope =
        `Assoc
          [ ("ok", `Bool false);
            ("code", `String "publish_complete_index_stale_cleanup_pending");
            ("message", `String message);
            ("details", expected_details) ]
      in
      Alcotest.(check string) "combined exact CLI contract"
        (Yojson.Safe.to_string expected_envelope)
        (Clamp.Cli_result.to_yojson envelope |> Yojson.Safe.to_string);
      let recovered = check_ok "retry durable publication cleanup" (run env) in
      Alcotest.(check string) "cleanup retry preserves published SHA" pushed
        recovered.commit;
      Alcotest.(check string) "cleanup retry clears state" ""
        (publication_refs env);
      local_change env "after-cleanup-recovery";
      let next = check_ok "normal publication after cleanup recovery" (run env) in
      Alcotest.(check bool) "later publication advances main" true
        (next.commit <> pushed);
      Alcotest.(check string) "later publication exact remote SHA" next.commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]);
      ignore
        (git_output env.bare
           [ "show";
             next.commit ^ ":knowledge/facts/after-cleanup-recovery.md" ]));
  with_environment "malformed-state" (fun env ->
      local_change env "state-shape";
      let original_ref =
        "refs/clamp/publish/" ^ thread_id ^ "/original"
      in
      git env.clone
        [ "update-ref"; original_ref;
          git_output env.clone [ "rev-parse"; "HEAD" ] ];
      ignore
        (check_error "partial atomic state" "publish_state_invalid" (run env));
      Alcotest.(check bool) "malformed state did not commit pending work" true
        (Sys.file_exists
           (Filename.concat env.clone "knowledge/facts/state-shape.md"));
      git env.clone [ "update-ref"; "-d"; original_ref ])

let validation_and_author_contract () =
  Alcotest.(check bool) "valid thread" true
    (Clamp.Publication.valid_thread_id thread_id);
  List.iter
    (fun value ->
      Alcotest.(check bool) ("invalid " ^ value) false
        (Clamp.Publication.valid_thread_id value))
    [ ""; "T-00000000-0000-0000-0000-00000000000g";
      "t-00000000-0000-0000-0000-000000000007" ];
  with_environment "author-contract" (fun env ->
      local_change env "authored";
      let report = check_ok "author" (run env) in
      Alcotest.(check string) "configured author"
        "Clamp Publisher <publisher@local.invalid>"
        (git_output env.bare
           [ "show"; "-s"; "--format=%an <%ae>"; report.commit ]))

let cli_contract () =
  with_environment "cli-json" (fun env ->
      local_change env "cli";
      let status, output, errors =
        capture_cli
          [ "publish"; "--repo"; env.clone; "--thread-id"; thread_id;
            "--json" ]
      in
      Alcotest.(check bool) "stale exit 6" true (status = Unix.WEXITED 6);
      Alcotest.(check string) "JSON stderr" "" errors;
      let json = Yojson.Safe.from_string output in
      let open Yojson.Safe.Util in
      Alcotest.(check string) "stale code" "publish_complete_index_stale"
        (json |> member "code" |> to_string);
      Alcotest.(check bool) "published true" true
        (json |> member "details" |> member "published" |> to_bool);
      let commit = json |> member "details" |> member "commit" |> to_string in
      Alcotest.(check string) "CLI exact durable SHA" commit
        (git_output env.bare [ "rev-parse"; "refs/heads/main" ]));
  with_environment "cli-human" (fun env ->
      local_change env "cli-human";
      let status, output, errors =
        capture_cli
          [ "publish"; "--repo"; env.clone; "--thread-id"; thread_id ]
      in
      Alcotest.(check bool) "human stale exit 6" true (status = Unix.WEXITED 6);
      Alcotest.(check string) "human stdout" "" output;
      Alcotest.(check string) "human stale message"
        "kb: Git publication succeeded, but the derived index is stale and must be synchronized later.\n"
        errors);
  with_environment "cli-conflict" (fun env ->
      let sentinel = "KNOWLEDGE_BODY_SECRET_SENTINEL" in
      write (Filename.concat env.clone "knowledge/facts/same.md")
        (fact "Same" sentinel);
      write (Filename.concat env.writer "knowledge/facts/same.md")
        (fact "Same" "Remote version.");
      ignore (commit_writer env "remote conflict");
      let status, output, errors =
        capture_cli
          [ "publish"; "--repo"; env.clone; "--thread-id"; thread_id;
            "--json" ]
      in
      Alcotest.(check bool) "conflict exit 3" true (status = Unix.WEXITED 3);
      Alcotest.(check string) "conflict stderr" "" errors;
      Alcotest.(check bool) "knowledge body absent" false
        (contains output sentinel);
      let json = Yojson.Safe.from_string output in
      let open Yojson.Safe.Util in
      Alcotest.(check string) "conflict code" "publish_conflict"
        (json |> member "code" |> to_string);
      Alcotest.(check (list string)) "body-free conflict paths"
        [ "knowledge/facts/same.md" ]
        (json |> member "details" |> member "paths" |> to_list
         |> List.map to_string))

let () =
  Alcotest.run "Phase 7 safe Git publication"
    [ ( "publication",
        [ Alcotest.test_case "clean, shallow, and out-of-date" `Quick
            clean_and_outdated;
          Alcotest.test_case "managed deletion" `Quick managed_deletion;
          Alcotest.test_case "exact bytes and inert transformation helper" `Quick
            exact_bytes_and_transform_guard;
          Alcotest.test_case "post-rebase TODO and exact-tree validation" `Quick
            post_rebase_validation;
          Alcotest.test_case "clean races and recovery" `Quick
            clean_races_and_recovery;
          Alcotest.test_case "generated TODO conflict" `Quick todo_conflict;
          Alcotest.test_case "resolve and preserve conflicts" `Quick
            conflict_resolution_and_preservation;
          Alcotest.test_case "preserved conflict cleanup recovery" `Quick
            conflict_preservation_cleanup_recovery;
          Alcotest.test_case "rejected conflict preservation push retry CLI"
            `Quick conflict_preservation_push_retry_cli;
          Alcotest.test_case "v1 publication state migration" `Quick
            v1_publication_state_migration;
          Alcotest.test_case "v1 post-abort conflict recovery" `Quick
            v1_post_abort_conflict_recovery;
          Alcotest.test_case "v2 preservation conservatism" `Quick
            v2_preservation_conservatism;
          Alcotest.test_case "reviewed Phase 7 CLI cross-version migration"
            `Quick reviewed_phase7_cli_cross_version;
          Alcotest.test_case "conflict owner-work preservation" `Quick
            conflict_owner_safety;
          Alcotest.test_case "content conflicts do not consume clean races" `Quick
            conflicts_do_not_consume_clean_races ] );
      ( "safety",
        [ Alcotest.test_case "refusals" `Quick safety_refusals;
          Alcotest.test_case "push and index failure semantics" `Quick
            push_failure_and_stale_index;
          Alcotest.test_case "atomic state interruption and cleanup" `Quick
            state_atomicity_and_cleanup;
          Alcotest.test_case "thread and author contract" `Quick
            validation_and_author_contract;
          Alcotest.test_case "CLI JSON and human contract" `Quick
            cli_contract ] ) ]
